// lib/endocrine-emergencies/glucose.ts
// Fellows' Survival Guide — GLUCOSE cluster: DKA, euglycemic DKA, HHS, hypoglycemia.
// EDUCATIONAL QUICK-REFERENCE ONLY. No PHI. See types.ts for the full notice.
//
// Guideline basis (reconciled 2026-08): the 2024 ADA/EASD/JBDS/AACE/DTS
// consensus report on hyperglycemic crises (the defining reference, adopted by
// ADA Standards of Care 2025–2026), the JBDS-IP DKA / HHS / hypoglycemia
// guidelines (2023), ADA Standards of Care in Diabetes 2025/2026 §6 & §16, and
// the Endocrine Society hypoglycemic-disorders clinical practice guideline.
// See `references` on each topic for the exact citations.

import type { Emergency } from './types'

export const GLUCOSE_EMERGENCIES: Emergency[] = [
  {
    id: 'dka',
    name: 'Diabetic Ketoacidosis (DKA)',
    category: 'glucose',
    summary: 'Insulin deficiency driving ketone overproduction and metabolic acidosis — diagnosed at glucose ≥200 mg/dL or ANY glucose in known diabetes (euglycemic DKA is now formally inside the criteria). The classic type-1 emergency, but increasingly seen in ketosis-prone type-2 and on SGLT2 inhibitors. Death is from the precipitant, cerebral edema (mainly children), hypokalemia, or aspiration — not the glucose itself.',
    firstActions: [
      'Assess ABCs and vitals; place on continuous cardiac monitoring, start strict intake/output, and check a bedside glucose PLUS capillary β-hydroxybutyrate now.',
      'Insert two large-bore IVs and start isotonic crystalloid — 0.9% NaCl or a balanced solution (LR / Plasma-Lyte) — at 500–1000 mL/h for the first 2–4 h.',
      'Draw STAT labs: glucose, electrolytes, BUN/Cr, venous pH, β-hydroxybutyrate, phosphate, Mg, CBC — plus ECG, troponin if indicated, and a septic screen to hunt the precipitant.',
      'Gate insulin on potassium: K <3.5 mmol/L → HOLD insulin and give KCl 10 mmol/h IV until K ≥3.5; K ≥3.5 → start a fixed-rate regular-insulin infusion at 0.1 U/kg/h (no routine bolus).',
      'Give basal insulin early — glargine 0.15–0.3 U/kg SC alongside the infusion — to shorten the drip and blunt rebound hyperglycemia.',
      'Stop any SGLT2 inhibitor on the medication list; treat euglycemia exactly as hyperglycemia — ketones and pH define the emergency, not the sugar.',
    ],
    features: [
      'Onset over hours: polyuria, polydipsia, weight loss, then nausea, vomiting, and diffuse abdominal pain (it can mimic a surgical abdomen and usually clears as the acidosis does).',
      'Kussmaul respirations (deep, sighing hyperventilation) and a fruity/acetone odor.',
      'Volume depletion: tachycardia, dry mucosa, hypotension; mental status ranges from alert to coma and tracks osmolality more than acidosis.',
      'Precipitant clues — the I-words: Infection, Infarction (MI/stroke), Infant (pregnancy), Indiscretion (diet/alcohol), Insulin omission, Iatrogenic drugs (steroids, SGLT2i, antipsychotics).',
    ],
    diagnosis: [
      '2024 ADA/EASD/JBDS/AACE/DTS consensus — all three required: (1) glucose ≥200 mg/dL (≥11.1 mmol/L) OR prior history of diabetes at any glucose; (2) β-hydroxybutyrate ≥3.0 mmol/L (or urine ketones ≥2+ if BOHB unavailable); (3) pH <7.3 AND/OR HCO3 <18 mmol/L. The anion gap has been REMOVED from the diagnostic criteria.',
      'What changed vs 2009 ADA: glucose threshold lowered from >250 to ≥200 mg/dL, the bicarb cutoff raised to <18, a numeric BOHB threshold added, and the anion gap dropped — euglycemic DKA (~10% of all DKA) is now formally inside the definition.',
      'β-hydroxybutyrate is the PREFERRED ketone measure — nitroprusside urine ketones see acetoacetate only, so they read falsely low early (β-OHB predominates) and falsely persistent in recovery (as β-OHB converts back to acetoacetate).',
      'A venous gas suffices (venous pH runs ~0.03 below arterial) — an arterial stick is rarely needed.',
      'Corrected Na = measured Na + 1.6 × ([glucose - 100] / 100): hyperglycemia pulls water in and dilutes sodium, so a normal measured Na in DKA actually signals a free-water deficit.',
      'Potassium is the trap: total-body K is depleted (~3–5 mmol/kg), yet serum K is often normal or HIGH on arrival (acidosis and insulin lack shift it out). It falls fast once insulin starts — anticipate it.',
      'Expect a stress leukocytosis that does not by itself mean infection, and a mildly raised lipase/amylase without pancreatitis. Grade severity by β-OHB, pH, HCO3, and mental status (GCS) — the 2024 unified scheme links grade to level of care (table).',
    ],
    management: [
      'Fluids first — 0.9% NaCl or balanced crystalloid at 500–1000 mL/h for the first 2–4 h, then 250–500 mL/h once hemodynamically stable. The deficit averages ~100 mL/kg (≈6–9 L): replace ~50% in the first 8–12 h, the rest over the next 12–16 h. Balanced solutions are now explicitly acceptable and are associated with faster resolution and less hyperchloremia.',
      'Potassium-gated insulin: K <3.5 mmol/L → HOLD insulin, replace KCl 10 mmol/h IV (central access + cardiac monitoring if faster), recheck q2h, and start insulin only when K ≥3.5; K 3.5–5.0 → add KCl 20–30 mmol per litre of fluid to hold K 4.0–5.0; K >5.0 → give no K and recheck q2h.',
      'Fixed-rate regular-insulin infusion (FRIII) 0.1 U/kg/h — a routine IV bolus is NO LONGER recommended; reserve a 0.1 U/kg bolus for a >1 h delay in starting the infusion or no available pump. Uncomplicated mild–moderate DKA can instead be treated with SC rapid-acting analog per protocol (lispro/aspart 0.3 U/kg then 0.2 U/kg q1h, or 0.2 U/kg q2h).',
      'Co-administer basal insulin EARLY — glargine 0.15–0.3 U/kg SC alongside the infusion; it shortens drip duration and rebound hyperglycemia without increasing hypoglycemia or hypokalemia.',
      'Titrate to KETONES, not glucose: expect β-OHB to fall ~0.5 mmol/L/h and glucose ~54 mg/dL/h; if not falling, check hydration and the line, then double the rate. When glucose reaches <250 mg/dL, REDUCE the infusion to 0.05 U/kg/h and ADD dextrose (D5–D10) — never stop the insulin while ketosis persists; ketone clearance is the endpoint.',
      'Monitor: bedside glucose q1h; electrolytes, BUN, venous pH, and phosphate q2–4h (K q2h while replacing); β-OHB q2–4h (JBDS q4h) — resolution is tracked by BOHB, not the anion gap; vitals, GCS, and strict I&O q1h.',
      'Adjuncts, not routine: bicarbonate ONLY if pH <7.0 (100 mmol sodium bicarbonate in 400 mL sterile water with 20 mmol KCl over 2 h, repeat to pH >7.0); phosphate only if <1.0 mg/dL with cardiac, respiratory, or hemolytic compromise; treat the precipitant.',
      'Resolution = β-OHB <0.6 mmol/L AND venous pH ≥7.3 (or HCO3 ≥18 mmol/L), ideally with glucose <200–250 mg/dL and the patient eating — anion-gap closure is no longer a criterion. Give basal + prandial SC insulin 1–2 h BEFORE stopping the infusion; TDD ≈0.5–0.6 U/kg/day (0.3 U/kg/day in elderly/frail/CKD; up to 0.75–1.0 in insulin resistance), ~50% basal / 50% prandial.',
    ],
    followUp: [
      'Pin and treat the trigger; deliver diabetes and sick-day education (never stop basal insulin; check ketones when ill).',
      'Confirm the SC basal overlap happened before the drip came off, then arrange outpatient diabetes follow-up.',
      'SGLT2 inhibitor: stopped on admission — do NOT routinely restart after DKA, and NEVER restart if the drug triggered the episode; if resumed, wait until fully recovered and eating with a ketone-monitoring plan. Perioperative hold: 3 days before surgery (4 days for ertugliflozin).',
      'Pump patients: restart CSII only after resolution criteria are met, the first SC meal bolus is given and tolerated, and not at bedtime (JBDS); verify the site and basal rates.',
    ],
    pearls: [
      'Never stop the insulin drip without SC overlap — the gap reopens within hours, and in type 1 the DKA can recur.',
      'Serum K on arrival hides a whole-body deficit; the danger window is the first few hours after insulin starts — recheck K q2h and keep it 4.0–5.0.',
      'Watch for cerebral edema (rare in adults, the killer in children; risk rises with low initial pCO2, high BUN, severe acidosis, bicarbonate treatment, and rapid osmolality fall): raise the head, give mannitol 0.5–1 g/kg IV over 20 min (or 3% saline 2.5–5 mL/kg), and slow the fluids.',
      'On an SGLT2 inhibitor the glucose may be near-normal — diagnose on ketones and pH, not the sugar (see euglycemic DKA).',
      'Bicarbonate is for pH <7.0 only — routine use is linked to cerebral edema and delays ketone clearance.',
    ],
    tables: [
      {
        title: 'DKA severity — 2024 unified classification (ADA/EASD/JBDS/AACE/DTS)',
        columns: ['Severity', 'β-OHB (mmol/L)', 'pH', 'HCO3 (mmol/L)', 'Mental status', 'Suggested level of care'],
        rows: [
          ['Mild', '3.0–6.0', '7.25–<7.30', '15–<18', 'Alert', 'Short stay / observation if no other illness'],
          ['Moderate', '≥3.0 (acidosis deeper)', '7.00–<7.25', '10–<15', 'Alert or drowsy', 'Ward / step-down; ICU per resources'],
          ['Severe', '≥3.0', '<7.00', '<10', 'Stupor or coma', 'ICU'],
        ],
        note: 'Venous pH is acceptable; if pH is unavailable, use bicarbonate. Grade by the most severe parameter present — mental status or pH <7.0 alone can mandate ICU. Selected alert patients with mild DKA and a treatable cause may be managed in ED/observation with SC insulin.',
      },
      {
        title: 'Potassium-guided insulin and repletion',
        columns: ['Serum K (mmol/L)', 'Insulin', 'Potassium'],
        rows: [
          ['< 3.5', 'HOLD until K ≥ 3.5', 'KCl 10 mmol/h IV (central access + cardiac monitoring if faster); recheck q2h'],
          ['3.5 – 5.0', 'Run at 0.1 U/kg/h', 'Add KCl 20–30 mmol per litre; target K 4.0–5.0'],
          ['> 5.0', 'Run at 0.1 U/kg/h', 'Give none; recheck q2h — insulin drives K into cells'],
        ],
        note: 'Total-body K deficit is ~3–5 mmol/kg whatever the first value. Insulin started before repleting a low potassium can precipitate arrhythmia and respiratory-muscle weakness.',
      },
      {
        title: 'Monitoring schedule and treatment targets',
        columns: ['Parameter', 'Frequency / target'],
        rows: [
          ['Bedside glucose', 'q1h while on IV insulin'],
          ['Potassium', 'q2h during replacement; keep 4.0–5.0 mmol/L'],
          ['Electrolytes, BUN, venous pH, phosphate', 'q2–4h'],
          ['β-hydroxybutyrate', 'q2–4h (JBDS q4h) — resolution marker, not anion gap'],
          ['Vitals, GCS, fluid balance', 'q1h; strict I&O'],
          ['Expected falls', 'β-OHB ~0.5 mmol/L/h · glucose ~54 mg/dL/h · osmolality ≤3–8 mOsm/kg/h'],
        ],
        note: 'If β-OHB or glucose is not falling at the expected rate, reassess hydration and the line before increasing the insulin rate.',
      },
    ],
    references: [
      {
        label: 'Hyperglycemic Crises in Adults With Diabetes: A Consensus Report',
        source: 'ADA/EASD/JBDS/AACE/DTS — Diabetologia',
        year: '2024',
        url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11343900/',
      },
      {
        label: '16. Diabetes Care in the Hospital: Standards of Care in Diabetes—2025',
        source: 'American Diabetes Association — Diabetes Care',
        year: '2025',
        url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11635037/',
      },
      {
        label: 'The Management of Diabetic Ketoacidosis in Adults (2nd rev., JBDS 02)',
        source: 'Joint British Diabetes Societies for Inpatient Care',
        year: '2023',
        url: 'https://abcd.care/sites/default/files/site_uploads/JBDS_Guidelines_Current/JBDS_02_DKA_Guideline_with_QR_code_March_2023.pdf',
      },
      {
        label: 'Hyperglycemic Crises in Diabetes (Endotext)',
        source: 'Endotext — NCBI Bookshelf',
        year: '2025',
        url: 'https://www.ncbi.nlm.nih.gov/books/NBK279052/',
      },
      {
        label: 'The 2024 Joint International Consensus Report on Hyperglycemic Crises in Adults With Diabetes: What We Need to Know',
        source: 'Cleveland Clinic Journal of Medicine',
        year: '2025',
        url: 'https://www.ccjm.org/content/92/3/152',
      },
    ],
    lastReviewed: '2026-08',
  },
  {
    id: 'euglycemic-dka',
    name: 'Euglycemic DKA (euDKA)',
    category: 'glucose',
    summary: 'Full ketoacidosis with glucose <200 mg/dL — the dangerous mimic that gets missed because the sugar looks reassuring. ~10% of all DKA, but ~35% of SGLT2-inhibitor-associated cases; think SGLT2 inhibitors above all, plus pregnancy, starvation/low-carb intake, alcohol, liver failure, and acute illness or surgery superimposed on diabetes.',
    firstActions: [
      'Check bedside glucose AND capillary β-hydroxybutyrate in any ill, vomiting, or acidotic patient with diabetes — a normal glucometer reading does not exclude DKA.',
      'Get a venous gas and full chemistry: euDKA = β-OHB ≥3.0 mmol/L + pH <7.3 and/or HCO3 <18 mmol/L, with glucose <200 mg/dL, in a patient with diabetes.',
      'Establish IV access and start isotonic crystalloid; plan dextrose EARLY (D5–D10), because insulin must run despite a normal glucose.',
      'Gate insulin on potassium exactly as in DKA: hold insulin and replete first if K <3.5 mmol/L; otherwise start the fixed-rate infusion at 0.1 U/kg/h.',
      'Stop the SGLT2 inhibitor immediately (or identify the alternative trigger — fasting, pregnancy, alcohol, pump failure).',
    ],
    features: [
      'The DKA syndrome — nausea/vomiting, abdominal pain, malaise, Kussmaul breathing, dehydration — but the glucose is normal or only mildly raised (<200 mg/dL).',
      'High-risk context is the tip-off: an SGLT2 inhibitor (canagliflozin / dapagliflozin / empagliflozin / ertugliflozin), pregnancy or lactation, reduced caloric or carbohydrate intake, heavy alcohol, liver failure, insulin-pump failure with reduced intake, recent surgery, or any acute illness in a person with diabetes.',
      'Overall ~10% of DKA is euglycemic; among SGLT2-inhibitor users ~35% present with glucose <200 mg/dL and ~71% at ≤250 mg/dL.',
    ],
    diagnosis: [
      'Ketonemia (β-OHB ≥3.0 mmol/L) + acidosis (pH <7.3 and/or HCO3 <18 mmol/L) with glucose <200 mg/dL — it qualifies under the 2024 criteria through the known-diabetes clause, so a normal glucose does NOT exclude DKA.',
      'Mechanism worth knowing: SGLT2 inhibitors lower glucose by urinary excretion (masking hyperglycemia) while raising glucagon and promoting lipolysis and ketogenesis — so the acidosis runs ahead of the sugar.',
      'Check β-hydroxybutyrate and a venous gas in ANY at-risk patient who is acidotic, vomiting, or unwell, whatever the glucometer shows — urine ketones lag and miss β-OHB.',
    ],
    management: [
      'Treat exactly as DKA but give dextrose EARLY: start D5–D10 (often D10) alongside the insulin infusion so insulin can clear ketones without dropping the glucose too low.',
      'Insulin infusion 0.1 U/kg/h to clear ketonemia — do NOT withhold insulin because the glucose is normal; the endpoint is ketone clearance, not glucose.',
      'Isotonic fluids for the deficit; potassium repletion and the same K-gated insulin rule (hold insulin if K <3.5 mmol/L) as in DKA.',
      'Stop the SGLT2 inhibitor immediately; do not restart during the acute illness — and never restart it if the drug triggered the episode.',
      'Continue insulin + dextrose until resolution: β-OHB <0.6 mmol/L AND venous pH ≥7.3 (or HCO3 ≥18 mmol/L), with the patient eating; overlap SC basal insulin 1–2 h before stopping the drip.',
    ],
    followUp: [
      'Counsel on SGLT2-inhibitor sick-day rules (stop during vomiting/fasting; check ketones when ill even if glucose is normal) and the perioperative hold — 3 days before surgery, 4 days for ertugliflozin; arrange home ketone testing for high-risk patients.',
      'Decide deliberately about resumption: the 2024 consensus says do NOT routinely restart after DKA (never if drug-triggered); ADA 2026 limits inpatient SGLT2i use after recovery to a heart-failure indication.',
      'Identify and treat the trigger (illness, fasting, surgery, pregnancy); in pregnancy involve OB, keep glucose 100–180 mg/dL with dextrose, and continue fetal monitoring.',
    ],
    pearls: [
      'A normal glucose does not exclude DKA — check ketones in any acidotic at-risk patient, especially on an SGLT2 inhibitor.',
      'Run insulin AND dextrose together from the start; the dextrose is what lets you keep clearing ketones.',
      'SGLT2-inhibitor ketoacidosis can surface days into a fast or after surgery and can persist after the drug is stopped (long tissue effect) — keep treating until ketones clear.',
      'SGLT2 inhibitors are not recommended for glycemic control in type 1 diabetes precisely because of this risk.',
    ],
    tables: [
      {
        title: 'Euglycemic DKA — triggers and what to do',
        columns: ['Trigger', 'Why glucose stays normal', 'Action'],
        rows: [
          ['SGLT2 inhibitor', 'Glucosuria masks hyperglycemia; glucagon + lipolysis drive ketones', 'Stop on admission; do not routinely restart; never if drug-triggered; hold 3 d pre-op (4 d ertugliflozin)'],
          ['Pregnancy', 'Lower glucose threshold; accelerated starvation ketosis', 'Same treatment; OB + fetal monitoring; dextrose to keep glucose 100–180 mg/dL'],
          ['Fasting / low-carb intake / vomiting', 'Carbohydrate deficit lowers insulin requirements', 'Early dextrose alongside insulin'],
          ['Alcohol / liver failure', 'Depleted glycogen; redox state favors β-OHB', 'Dextrose early; glucagon ineffective if glycogen-depleted'],
          ['Insulin pump failure + reduced intake', 'Absolute insulin deficiency at near-normal glucose', 'IV insulin; verify site and basal rates before restarting the pump'],
        ],
        note: 'Whatever the trigger, the diagnostic criteria (β-OHB ≥3.0 mmol/L + pH <7.3 / HCO3 <18 mmol/L) and the treatment endpoint (ketone clearance) are identical to DKA.',
      },
    ],
    references: [
      {
        label: 'Hyperglycemic Crises in Adults With Diabetes: A Consensus Report',
        source: 'ADA/EASD/JBDS/AACE/DTS — Diabetologia',
        year: '2024',
        url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11343900/',
      },
      {
        label: 'The Management of Diabetic Ketoacidosis in Adults (2nd rev., JBDS 02)',
        source: 'Joint British Diabetes Societies for Inpatient Care',
        year: '2023',
        url: 'https://abcd.care/sites/default/files/site_uploads/JBDS_Guidelines_Current/JBDS_02_DKA_Guideline_with_QR_code_March_2023.pdf',
      },
      {
        label: '16. Diabetes Care in the Hospital: Standards of Care in Diabetes—2026',
        source: 'American Diabetes Association — Diabetes Care',
        year: '2026',
        url: 'https://diabetesjournals.org/care/article/49/Supplement_1/S339/163925/16-Diabetes-Care-in-the-Hospital-Standards-of-Care',
      },
      {
        label: 'Euglycemic Diabetic Ketoacidosis: A Review',
        source: 'Current Diabetes Reviews',
        year: '2017',
        url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC8292703/',
      },
      {
        label: 'Hyperglycemic Crises in Diabetes (Endotext)',
        source: 'Endotext — NCBI Bookshelf',
        year: '2025',
        url: 'https://www.ncbi.nlm.nih.gov/books/NBK279052/',
      },
    ],
    lastReviewed: '2026-08',
  },
  {
    id: 'hhs',
    name: 'Hyperosmolar Hyperglycemic State (HHS)',
    category: 'glucose',
    summary: 'Extreme hyperglycemia (≥600 mg/dL) and hyperosmolality (≥320 mOsm/kg) with little or no ketosis — typically an older type-2 patient evolving over days, often with infection and poor access to water. It builds slower than DKA, dehydrates far more (deficit ~8–12 L), and carries 10–20% mortality. Fluids are the treatment; insulin comes second and lower.',
    firstActions: [
      'Assess ABCs, mental status (GCS), and volume; place on a monitor with strict I&O — neuro status tracks osmolality and is the best bedside severity gauge.',
      'Insert two large-bore IVs and start 0.9% NaCl (or balanced crystalloid) at 500–1000 mL/h — fluids alone will drop the glucose substantially in the first hours.',
      'Draw STAT labs: glucose, electrolytes, BUN/Cr, venous pH, β-hydroxybutyrate, and osmolality (measured, or calculate 2×Na + glucose/18); ECG, septic screen, and a medication review for the precipitant.',
      'Check potassium before any insulin — hold insulin and replete if K <3.5 mmol/L.',
      'Do NOT rush insulin: start a fixed-rate infusion at 0.05 U/kg/h ONLY when glucose stops falling with fluids alone — or immediately at 0.1 U/kg/h if β-OHB ≥1.0 mmol/L (DKA–HHS overlap).',
      'Start pharmacologic VTE prophylaxis (LMWH unless contraindicated) — thrombosis is a leading killer in HHS.',
    ],
    features: [
      'Days to weeks of polyuria and polydipsia ending in profound dehydration; the trigger is frequently infection (pneumonia, UTI), an MI or stroke, missed medication, or a hyperglycemic drug (steroids, diuretics, atypical antipsychotics).',
      'Neurologic dominance: lethargy, confusion, focal deficits, seizures, or coma — the depression of consciousness tracks OSMOLALITY (obtunded patients usually have effective osm >320–340).',
      'Minimal ketotic symptoms and little Kussmaul breathing — the acidosis is mild or absent, which is what separates it clinically from DKA.',
      'Up to half of HHS shows DKA–HHS overlap features — some ketosis or mild acidosis does not change the fluid-first logic.',
    ],
    diagnosis: [
      '2024 consensus — all required: glucose ≥600 mg/dL (≥33.3 mmol/L; JBDS uses ≥30 mmol/L / 540 mg/dL); effective serum osmolality ≥320 mOsm/kg; β-OHB <3.0 mmol/L (urine ketones ≤2+); pH ≥7.3 AND HCO3 ≥18 mmol/L (JBDS: HCO3 >15).',
      'Effective osm = 2 × Na + glucose/18 (BUN is excluded — urea crosses cell membranes and does not drive water shifts).',
      'Mental status tracks osmolality — an obtunded patient usually has effective osm >320–340; the 2024 report sets no formal severity strata for HHS (unlike DKA).',
      'Corrected Na = measured Na + 1.6 × ([glucose - 100] / 100) — a corrected Na that is high, or that fails to rise appropriately as glucose falls, guides fluid choice and reveals the true free-water deficit.',
      'Estimate the deficit: ~100–220 mL/kg (~8–12 L in an adult). Work up the precipitant (cultures, ECG/troponin, medication review).',
    ],
    management: [
      'FLUIDS FIRST — the dominant therapy: 0.9% NaCl (or balanced crystalloid) at 500–1000 mL/h for the first 2–4 h, then 250–500 mL/h titrated to corrected Na and hemodynamics. Replace ~50% of the deficit in the first 12 h and the rest over the next 12 h (slower in elderly, heart failure, CKD).',
      'Track corrected sodium: if it is high or rising, switch to 0.45% NaCl after initial resuscitation (JBDS approach); add D5 (with 0.45% NaCl) when glucose reaches 250–300 mg/dL.',
      'Respect the correction rate limits: glucose fall ≤90–120 mg/dL/h (≤5 mmol/L/h), osmolality fall 3–8 mOsm/kg/h, sodium rise ≤10 mmol/L per 24 h — faster correction risks cerebral edema and osmotic demyelination.',
      'INSULIN SECOND and LOWER: fixed-rate IV insulin 0.05 U/kg/h ONLY when glucose is no longer falling with fluids alone (fluids drop glucose 90–200 mg/dL/h initially); start immediately at 0.1 U/kg/h if β-OHB ≥1.0 mmol/L or DKA–HHS overlap. No bolus — premature insulin shifts water intracellularly and risks vascular collapse. If the fall is <5 mmol/L/h on insulin, recheck hydration before doubling the rate.',
      'Potassium: same thresholds as DKA — hold insulin if K <3.5 mmol/L until repleted; add KCl 20–30 mmol per litre to keep K 4.0–5.0 mmol/L.',
      'No routine bicarbonate or phosphate. Give LMWH VTE prophylaxis to EVERY HHS patient (high thrombosis risk). Treat the precipitant.',
      'Monitor: glucose q1h; electrolytes and β-OHB q2–4h; CALCULATE osmolality q4h; neuro status and strict I&O q1h. Transition to SC insulin as in DKA (basal given with 1–2 h overlap) but with a lower TDD, 0.3–0.5 U/kg/day — HHS patients are often insulin-sensitive.',
    ],
    followUp: [
      'Treat the precipitant and provide diabetes education; many patients transition to oral agents or modest insulin once recovered.',
      'Mind the heightened thrombosis and mortality risk — continue VTE prophylaxis through the admission; mental-status recovery lags the labs, and a persistent deficit suggests an unresolved cause or a CNS event.',
      'Confirm the 2024 resolution criteria before stepping down: osmolality <300 mOsm/kg, glucose <250 mg/dL, urine output >0.5 mL/kg/h, and cognition recovered (table).',
    ],
    pearls: [
      'Volume first — fluids, not insulin, are the main early glucose-lowering tool; going in insulin-heavy invites vascular collapse.',
      'Respect the osmolality and sodium correction limits; if corrected Na fails to rise appropriately as glucose falls, your fluid is too hypotonic.',
      'Mixed DKA–HHS is common (up to 50% of HHS) — with significant ketoacidosis (β-OHB ≥1.0 mmol/L), treat as DKA (0.1 U/kg/h insulin) while keeping the HHS correction-rate limits.',
      'HHS kills through thrombosis — DVT/PE, stroke, MI; universal prophylaxis is part of the treatment, not an afterthought.',
    ],
    tables: [
      {
        title: 'DKA vs HHS at a glance (2024 criteria)',
        columns: ['Feature', 'DKA', 'HHS'],
        rows: [
          ['Typical patient', 'Younger, type 1 (or ketosis-prone T2)', 'Older, type 2'],
          ['Onset', 'Hours', 'Days to weeks'],
          ['Glucose', '≥200 mg/dL (or any glucose with known DM)', '≥600 mg/dL (JBDS ≥540)'],
          ['Ketones / β-OHB', '≥3.0 mmol/L', '<3.0 mmol/L (urine ≤2+)'],
          ['pH', '< 7.30', '≥ 7.30'],
          ['HCO3', '< 18 mmol/L', '≥ 18 mmol/L (JBDS >15)'],
          ['Effective osm', 'Variable', '≥ 320 mOsm/kg'],
          ['Fluid deficit', '~6–9 L (~100 mL/kg)', '~8–12 L (~100–220 mL/kg)'],
          ['Insulin', '0.1 U/kg/h at once (no routine bolus)', '0.05 U/kg/h, delayed until fluids stop lowering glucose'],
          ['Mortality', '~1%', '10–20%'],
        ],
        note: 'A mixed DKA–HHS picture is common; when significant ketoacidosis is present, manage as DKA while keeping the HHS correction-rate limits.',
      },
      {
        title: 'Resolution criteria — DKA vs HHS (2024 consensus)',
        columns: ['Criterion', 'DKA', 'HHS'],
        rows: [
          ['Ketones', 'β-OHB <0.6 mmol/L', 'β-OHB <1.0 mmol/L (if any ketosis was present)'],
          ['Acid–base', 'Venous pH ≥7.3 or HCO3 ≥18 mmol/L', 'pH ≥7.3 (if acidosis was present)'],
          ['Glucose', '<200–250 mg/dL', '<250 mg/dL (13.9 mmol/L)'],
          ['Osmolality', '—', '<300 mOsm/kg'],
          ['Clinical', 'Eating; ready for SC transition', 'Urine output >0.5 mL/kg/h AND cognitive status recovered'],
        ],
        note: 'Formal HHS resolution criteria were introduced for the first time in the 2024 consensus. In both, give basal SC insulin with a 1–2 h overlap before stopping the infusion.',
      },
    ],
    references: [
      {
        label: 'Hyperglycemic Crises in Adults With Diabetes: A Consensus Report',
        source: 'ADA/EASD/JBDS/AACE/DTS — Diabetologia',
        year: '2024',
        url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11343900/',
      },
      {
        label: 'Management of Hyperosmolar Hyperglycaemic State (HHS) in Adults: An Updated Guideline from the JBDS for Inpatient Care Group',
        source: 'JBDS-IP — Diabetic Medicine',
        year: '2023',
        url: 'https://onlinelibrary.wiley.com/doi/10.1111/dme.15005',
      },
      {
        label: 'Hyperglycemic Crises in Diabetes (Endotext)',
        source: 'Endotext — NCBI Bookshelf',
        year: '2025',
        url: 'https://www.ncbi.nlm.nih.gov/books/NBK279052/',
      },
      {
        label: 'The 2024 Joint International Consensus Report on Hyperglycemic Crises in Adults With Diabetes: What We Need to Know',
        source: 'Cleveland Clinic Journal of Medicine',
        year: '2025',
        url: 'https://www.ccjm.org/content/92/3/152',
      },
      {
        label: 'Hyperosmolar Hyperglycemic State (HHS)',
        source: 'Merck Manual Professional',
        year: '2024',
        url: 'https://www.merckmanuals.com/professional/endocrine-and-metabolic-disorders/diabetes-mellitus-and-disorders-of-carbohydrate-metabolism/hyperosmolar-hyperglycemic-state-hhs',
      },
    ],
    lastReviewed: '2026-08',
  },
  {
    id: 'hypoglycemia',
    name: 'Hypoglycemia',
    category: 'glucose',
    summary: 'Low plasma glucose with adrenergic + neuroglycopenic symptoms. The approach splits sharply by context: in diabetes it is a clinical/iatrogenic diagnosis managed per ADA severity levels; in a non-diabetic it must be PROVEN (Whipple\'s triad) and then worked up with a critical sample drawn while glucose is <55 mg/dL.',
    firstActions: [
      'In a symptomatic diabetic, treat first and confirm later — never delay treatment in an obtunded patient; send a lab plasma glucose if it does not slow you down.',
      'Conscious and able to swallow: give 15–20 g fast-acting carbohydrate (glucose tablets preferred) — 5–10 g if on a pump/AID with a mild episode — and recheck in 10–15 min.',
      'Unconscious, seizing, or NPO: give IV dextrose — 150–200 mL of 10% (D10) or 75–100 mL of 20% (D20) over 15 min (JBDS-preferred; D50 25 g is the US ED alternative) — recheck q10–15 min and repeat.',
      'No IV access: give glucagon — Baqsimi 3 mg intranasal, Gvoke 1 mg SC, dasiglucagon (Zegalogue) 0.6 mg SC, or the reconstituted 1 mg kit IM/SC.',
      'In a NON-diabetic: draw the critical sample (glucose, insulin, C-peptide, proinsulin, β-OHB, sulfonylurea screen ± insulin antibodies ± cortisol) BEFORE giving dextrose, if it will not delay treatment.',
      'If a sulfonylurea or long-acting insulin is the cause, admit for 24–48 h of monitoring — recurrence is the rule, not the exception.',
    ],
    features: [
      'Adrenergic / autonomic (earlier, glucose ~55–70 mg/dL): tremor, palpitations, sweating, anxiety, hunger, pallor.',
      'Neuroglycopenic (lower): confusion, behavior/personality change, blurred or double vision, slurred speech, seizures, coma.',
      'Whipple\'s triad = (1) symptoms/signs of hypoglycemia + (2) a low plasma glucose by a reliable lab method + (3) resolution when glucose is raised. Required before working up a non-diabetic.',
      'Hypoglycemia unawareness: recurrent lows / hypoglycemia-associated autonomic failure blunt the adrenergic warning, so neuroglycopenia becomes the first sign — common in long-standing T1DM and tight control.',
    ],
    diagnosis: [
      'Define severity (ADA 2025/2026, diabetes context): Level 1 = glucose <70 and ≥54 mg/dL (3.9–3.0 mmol/L), the alert value; Level 2 = <54 mg/dL (3.0 mmol/L), the clinically significant neuroglycopenic threshold (IHSG 2017); Level 3 = severe cognitive impairment requiring EXTERNAL assistance for recovery — no fixed glucose cutoff. See table.',
      'DIABETIC patients: a CLINICAL, contextual diagnosis — almost always iatrogenic from insulin or an insulin secretagogue (sulfonylurea, meglitinide). No endocrine work-up is needed; instead pin the precipitant: missed/late meal, exercise, dose error, renal or hepatic impairment, alcohol, or hypoglycemia unawareness.',
      'NON-DIABETIC patients: first PROVE true hypoglycemia with Whipple\'s triad — symptoms, a low LAB plasma glucose, and relief when glucose is raised. Do not work up asymptomatic low meter readings or postprandial symptoms without a documented low glucose.',
      'NON-DIABETIC — draw the CRITICAL SAMPLE at the moment plasma glucose is <55 mg/dL, ideally before treatment: plasma glucose, insulin, C-peptide, proinsulin, β-hydroxybutyrate, sulfonylurea/meglitinide screen, insulin antibodies (if autoimmune or surreptitious suspected), and the glucose response to 1 mg IV glucagon; add cortisol, IGF-2 (with the IGF-2:IGF-1 ratio), growth hormone, and alcohol level as indicated.',
      'NON-DIABETIC — frame the differential by appearance: ill/medicated → drugs (quinolones, pentamidine, quinine, tramadol, alcohol), organ failure (hepatic/renal/cardiac), sepsis, cortisol or GH deficiency, or a non-islet-cell tumor (IGF-2). Healthy-appearing → endogenous hyperinsulinism: insulinoma, surreptitious sulfonylurea, insulin autoimmune syndrome, or post-bariatric hyperinsulinemic hypoglycemia.',
      'Interpret the critical sample at glucose <55 mg/dL using the grid below — the pattern of insulin, C-peptide, proinsulin, β-OHB, and the post-glucagon glucose rise separates the causes.',
    ],
    management: [
      'Conscious, mild (the 15-15 rule): 15–20 g fast-acting carbohydrate (glucose tablets preferred; or 60 mL glucose shot, 150–200 mL fruit juice, 3–4 tsp sugar in water); recheck in 10–15 min and repeat up to 3 times, then give long-acting carbohydrate (biscuits, toast, milk, or the next meal). On a pump/AID or CGM with a mild episode, 5–10 g may suffice — overtreatment causes rebound hyperglycemia.',
      'On acarbose or miglitol: use PURE glucose (dextrose) — sucrose/table sugar is ineffective while α-glucosidase is blocked.',
      'Severe (Level 3) or no oral route: IV dextrose is preferred when access exists — 150–200 mL D10 or 75–100 mL D20 over 15 min, recheck q10–15 min and repeat (JBDS preference: less tissue toxicity and less glycemic overshoot than D50; US ED practice also uses D50 25 g / 50 mL). Without access: glucagon 1 mg IM/SC, Baqsimi 3 mg intranasal, Gvoke 1 mg SC, or dasiglucagon 0.6 mg SC (repeat dasiglucagon once if no response in 15 min).',
      'After recovery: give long-acting carbohydrate — double the portion if glucagon was given (it depletes glycogen) — and do NOT simply omit the next insulin dose; review the regimen.',
      'Glucagon caveat: it fails when hepatic glycogen is depleted (alcohol, starvation/malnutrition, severe liver disease, adrenal insufficiency) and is less effective with sulfonylureas — IV dextrose is the definitive therapy there.',
      'Sulfonylurea-induced or refractory/recurrent: admit; continuous dextrose infusion; add octreotide (e.g., 50 µg SC q6–8h) to suppress insulin secretion; monitor 24–48 h (longer in CKD) — recurrence up to 24–36 h.',
      'Inpatient (ADA §16): a nurse-initiated protocol treats any glucose <70 mg/dL — stop the insulin infusion, recheck per protocol, document in the EHR, and REVIEW the treatment plan to prevent the next (Level 3) event.',
      'Cause-directed (non-diabetic): per the critical-sample result — insulinoma → localize and resect; sulfonylurea → stop the drug + observe; NICTH → treat the tumor ± glucocorticoid/GH; adrenal insufficiency → hydrocortisone; post-bariatric → dietary change, acarbose, or diazoxide.',
    ],
    followUp: [
      'Diabetic: review the insulin/secretagogue regimen; screen for and reverse hypoglycemia unawareness (several weeks of scrupulous hypoglycemia avoidance can partially restore awareness); consider CGM; prescribe glucagon and TRAIN family/caregivers — every at-risk patient should have it (ADA Rec 6.12), and 2026 guidance adds oral glucose to first-aid kits.',
      'Non-diabetic with proven Whipple\'s triad: complete the critical-sample work-up, then localize confirmed endogenous hyperinsulinism (CT/MRI, endoscopic ultrasound, and — if needed — selective arterial calcium stimulation for insulinoma).',
      'If no spontaneous episode was captured, admit for a supervised 72-hour fast (protocol outline in tables); for a postprandial/reactive pattern (e.g., post–gastric bypass), use a mixed-meal tolerance test instead — and never fast a patient whose diabetes regimen can itself cause hypoglycemia.',
      'Document driving/safety counseling for recurrent severe events; in CKD/ESRD expect prolonged risk (decreased insulin clearance and renal gluconeogenesis) and avoid orange juice for treatment (potassium load).',
    ],
    pearls: [
      'In any non-diabetic, establish Whipple\'s triad first — do not chase a glucometer number; confirm with a lab plasma glucose.',
      'The critical sample is only interpretable if drawn WHILE glucose is <55 mg/dL — a panel sent at normal glucose is uninterpretable.',
      'High insulin + LOW C-peptide = exogenous (factitious or iatrogenic) insulin. High insulin + HIGH C-peptide + positive drug screen = sulfonylurea — the great insulinoma mimic.',
      'LOW β-hydroxybutyrate (≤2.7 mmol/L) plus a glucose rise ≥25 mg/dL after 1 mg IV glucagon = insulin-mediated hypoglycemia (insulin is antiketogenic and preserves hepatic glycogen).',
      'Glucagon can fail (glycogen-depleted or sulfonylurea patients) — dextrose is definitive; sulfonylurea lows recur for many hours, so observe/admit long enough.',
      'β-blockers blunt the adrenergic warning symptoms but not the hypoglycemia itself — Level 3 events can arrive without a prodrome.',
    ],
    tables: [
      {
        title: 'Severity levels (ADA — diabetes context)',
        columns: ['Level', 'Plasma glucose', 'Clinical meaning'],
        rows: [
          ['Level 1 (alert)', '<70 and ≥54 mg/dL (3.9–3.0 mmol/L)', 'Treat with fast carbohydrate; reassess regimen.'],
          ['Level 2 (clinically significant)', '<54 mg/dL (3.0 mmol/L)', 'Neuroglycopenia threshold (IHSG 2017); serious, needs prompt correction.'],
          ['Level 3 (severe)', 'No fixed cutoff', 'Cognitive/physical impairment requiring external assistance to recover.'],
        ],
        note: 'Levels guide diabetes management. In a non-diabetic, use Whipple\'s triad and the <55 mg/dL work-up threshold instead.',
      },
      {
        title: 'Glucagon products — the no-reconstitution era',
        columns: ['Product', 'Adult dose', 'Route / form', 'Notes'],
        rows: [
          ['Glucagon kit (powder)', '1 mg (1 mL)', 'IM / SC / IV after reconstitution', 'Multi-step mixing; nausea common'],
          ['Gvoke (pre-filled syringe / HypoPen)', '1 mg/0.2 mL', 'SC, ready-to-use liquid', 'No mixing; 2–12 y and <45 kg: 0.5 mg'],
          ['Baqsimi (nasal powder)', '3 mg, single actuation', 'Intranasal, one nostril', 'No injection; works if unconscious; ≥4 y same dose; avoid with nasal congestion/decongestants'],
          ['Zegalogue (dasiglucagon)', '0.6 mg/0.6 mL', 'SC auto-injector / syringe', 'Repeat 0.6 mg if no response in 15 min; ≥6 y same dose'],
        ],
        note: 'Glucagon needs hepatic glycogen — it underperforms with sulfonylureas, alcohol, starvation, severe liver disease, and adrenal insufficiency; prefer IV dextrose there. Prescribe for every at-risk patient and train caregivers.',
      },
      {
        title: 'Critical-sample interpretation (non-diabetic, drawn at glucose <55 mg/dL)',
        columns: ['Cause', 'Insulin', 'C-peptide', 'Proinsulin', 'β-OHB', 'Δ glucose post-glucagon', 'Key clue'],
        rows: [
          ['Endogenous hyperinsulinism (insulinoma, post-bariatric, nesidioblastosis)', '↑ (≥3 µU/mL)', '↑ (≥0.6 ng/mL)', '↑ (≥5 pmol/L)', '↓ (≤2.7 mmol/L)', '↑ ≥25 mg/dL', 'Drug screen neg, Ab neg'],
          ['Exogenous insulin (factitious)', '↑↑ (often very high)', '↓ suppressed (<0.6)', '↓', '↓', '↑', 'High insulin with LOW C-peptide'],
          ['Sulfonylurea / meglitinide', '↑', '↑', '↑', '↓', '↑', 'Drug screen POSITIVE (mimics insulinoma)'],
          ['Insulin autoimmune', '↑↑ (assay-dependent)', '↑', 'Variable', '↓', '↑', 'Anti-insulin antibodies POSITIVE'],
          ['NICTH / IGF-2-mediated', '↓', '↓', '↓', '↑ (>2.7, ketotic)', 'No rise', '↑ IGF-2 : IGF-1 ratio; large tumor'],
          ['Non-insulin (alcohol, organ failure, cortisol/GH deficiency, sepsis)', '↓ (<3)', '↓ (<0.6)', '↓ (<5)', '↑', 'No rise (<25)', 'Clinical context; check AM cortisol'],
        ],
        note: 'Thresholds (Endocrine Society) apply when plasma glucose is <55 mg/dL. Insulin µU/mL, C-peptide ng/mL, proinsulin pmol/L, β-OHB mmol/L. ↑ raised, ↓ low/suppressed. Suppressed β-OHB and a glycemic response to glucagon reflect insulin action and help when insulin/C-peptide are borderline.',
      },
      {
        title: '72-hour supervised fast — protocol outline (non-diabetic workup)',
        columns: ['Step', 'Protocol'],
        rows: [
          ['Setup', 'Inpatient or closely supervised; stop nonessential meds; noncaloric, noncaffeinated fluids only; keep the patient active while awake'],
          ['Sampling', 'Plasma glucose q6h until <60 mg/dL (3.3 mmol/L), then q1–2h (meter with lab confirmation of low values)'],
          ['Endpoint', 'End at glucose <55 mg/dL WITH symptoms/signs (Whipple\'s triad) — or at 72 h'],
          ['Critical samples', 'At endpoint: glucose, insulin, C-peptide, proinsulin, β-OHB, sulfonylurea screen ± insulin antibodies ± cortisol / IGF-2'],
          ['Glucagon test', 'Then 1 mg glucagon IV; glucose q10 min ×3 — a rise ≥25 mg/dL suggests insulin-mediated; then feed'],
          ['Yield (insulinoma)', '~1/3 positive by 12 h · ~80% by 24 h · ~90% by 48 h · ~99% by 72 h'],
        ],
        note: 'Gold standard when no spontaneous episode is captured. Use a mixed-meal tolerance test instead for postprandial (reactive) hypoglycemia. Never fast patients at risk from their own diabetes regimen.',
      },
    ],
    references: [
      {
        label: '6. Glycemic Goals and Hypoglycemia: Standards of Care in Diabetes—2025',
        source: 'American Diabetes Association — Diabetes Care',
        year: '2025',
        url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11635034/',
      },
      {
        label: '6. Glycemic Goals, Hypoglycemia, and Hyperglycemic Crises: Standards of Care in Diabetes—2026',
        source: 'American Diabetes Association — Diabetes Care',
        year: '2026',
        url: 'https://diabetesjournals.org/care/article/49/Supplement_1/S132/163927/6-Glycemic-Goals-Hypoglycemia-and-Hyperglycemic',
      },
      {
        label: 'The Hospital Management of Hypoglycaemia in Adults with Diabetes Mellitus (6th ed., JBDS 01)',
        source: 'Joint British Diabetes Societies for Inpatient Care',
        year: '2023',
        url: 'https://abcd.care/sites/default/files/site_uploads/JBDS_Guidelines_Current/JBDS_01_Hypo_Guideline_with_QR_code_January_2023.pdf',
      },
      {
        label: 'Evaluation and Management of Adult Hypoglycemic Disorders: An Endocrine Society Clinical Practice Guideline',
        source: 'Endocrine Society — J Clin Endocrinol Metab',
        year: '2009',
        url: 'https://academic.oup.com/jcem/article/94/3/709/2590920',
      },
      {
        label: '72 Hour Fast for Investigation of Spontaneous Hypoglycaemia in Adults (v3)',
        source: 'NNUH/JPUH/QEHKL Joint Trust Guideline',
        year: '2023',
        url: 'https://www.nnuh.nhs.uk/publication/download/72-hour-fast-for-investigation-of-spontaneous-hypoglycaemia-in-adults-jcg0329-v3/',
      },
    ],
    lastReviewed: '2026-08',
  },
]
