// lib/endocrine-emergencies/mineral-pituitary.ts
// Fellows' Survival Guide — mineral & pituitary emergencies cluster:
// hypercalcemic crisis, acute hypocalcemia, severe hyponatremia/SIADH,
// hypernatremia, hyperkalemia, hypokalemia, pituitary apoplexy, and
// diabetes insipidus (AVP deficiency).
// EDUCATIONAL QUICK-REFERENCE ONLY. No PHI. See types.ts for the full notice.
//
// Guideline basis (reconciled 2026-08): 2023 Endocrine Society hypercalcemia
// of malignancy guideline; Fifth International Workshop on PHPT (2022);
// Second International Workshop on Hypoparathyroidism (2022); 2014 European +
// 2013 US hyponatremia guidance (still the anchors); UK Kidney Association
// acute hyperkalaemia guideline (Oct 2023); UK pituitary apoplexy guideline
// (2011) with 2024 reviews; NEJM 2023 CARGO copeptin trial + 2022 AVP-D
// renaming.

import type { Emergency } from './types'

export const MINERAL_PITUITARY_EMERGENCIES: Emergency[] = [
  // ───────────────────────────── CALCIUM ─────────────────────────────
  {
    id: 'hypercalcemic-crisis',
    name: 'Hypercalcemic Crisis',
    category: 'calcium',
    summary: 'Severe hypercalcemia (typically corrected Ca >14 mg/dL) PLUS organ dysfunction — obtundation, AKI/oliguria, short-QT arrhythmia, profound volume depletion — most often malignancy or primary hyperparathyroidism. The treatment triad is rehydrate, inhibit bone resorption, and treat the cause; hypercalcemia itself drives a nephrogenic diuresis that worsens the calcium in a vicious cycle.',
    firstActions: [
      'Large-bore IV access + isotonic saline: 1–2 L bolus, then 200–500 mL/h (adjust for age, CHF, CKD) targeting urine output 100–150 mL/h — restores GFR and drives calciuresis; fluids alone typically lower Ca 1–2 mg/dL.',
      'If severe (Ca >14 mg/dL) or symptomatic: calcitonin 4 IU/kg SC/IM q12h (may increase to 6–8 IU/kg q6–12h) — onset 2–4 h, bridges the days until the antiresorptive works; tachyphylaxis by 48–72 h.',
      'Draw intact PTH FIRST plus PTHrP, 25-OHD, 1,25(OH)2D, phosphate, Mg, creatinine, ± SPEP/UPEP — PTH is the fork in the road (PTH-mediated vs PTHrP/malignancy vs calcitriol-mediated).',
      'ECG + telemetry (short QT, arrhythmia risk); stop culprit drugs (thiazides, lithium, calcium/vitamin D supplements) and mobilize — immobilization perpetuates resorption.',
      'Only AFTER volume repletion: zoledronic acid 4 mg IV over ≥15 min — or denosumab 60–120 mg SC, which the 2023 Endocrine Society suggests OVER IV bisphosphonate for acute hypercalcemia of malignancy and is the agent of choice when eGFR <30 or on dialysis.',
      'PHPT crisis: call endocrine surgery early — urgent parathyroidectomy is indicated after medical stabilization.',
    ],
    features: [
      'The classic "stones, bones, abdominal groans, and psychiatric overtones" — nephrolithiasis, bone pain, nausea/vomiting/constipation/anorexia, and fatigue, confusion, or depression.',
      'Crisis = severe hypercalcemia plus end-organ dysfunction: altered mental status to coma, AKI/oliguria, and cardiac effects.',
      'Polyuria and dehydration: hypercalcemia causes a nephrogenic diabetes insipidus and natriuresis, so volume depletion concentrates calcium further.',
      'Cardiac: a SHORT QT interval, bradyarrhythmia, heart block at very high levels, and increased sensitivity to digoxin.',
      'Symptoms track the RATE of rise as much as the absolute value — a fast rise to 13 can be sicker than a chronic 14.',
    ],
    diagnosis: [
      'Confirm with corrected calcium — corrected Ca (mg/dL) = measured Ca + 0.8 × (4.0 − albumin g/dL) — or better, an IONIZED calcium in ICU, acid-base disturbance, or CKD, where albumin correction is unreliable.',
      'Severity bands (Endocrine Society 2023, malignancy): mild 10.5 to <12.0 mg/dL, moderate 12.0–14.0, severe >14.0 (table).',
      'PTH first: HIGH or inappropriately normal PTH → PTH-dependent (primary hyperparathyroidism, parathyroid carcinoma, lithium, familial hypocalciuric hypercalcemia); SUPPRESSED PTH → PTH-independent — then send PTHrP, 25-OHD, 1,25(OH)2D, and SPEP/UPEP with imaging.',
      'Malignancy mechanisms: PTHrP (humoral hypercalcemia of malignancy), osteolytic metastases, and calcitriol production by lymphoma or granulomatous disease.',
      'Fifth International Workshop (2022): normocalcemic PHPT is recognized, and surgical criteria are updated (24-h urine Ca cutoffs now >300 mg men / >250 mg women) — check PTH before discharge even when malignancy is suspected; concurrent PHPT is common.',
      'ECG for a short QT; check renal function, phosphate, and magnesium.',
    ],
    management: [
      'Volume restoration is the mainstay: 0.9% NaCl 1–2 L bolus then 200–500 mL/h titrated to urine output 100–150 mL/h — restores GFR and promotes calciuresis.',
      'Calcitonin (salmon) 4 IU/kg SC/IM q12h (up to 6–8 IU/kg q6–12h) for severe/symptomatic cases: lowers Ca ~0.5–1.5 mg/dL within 2–4 h but tachyphylaxes by 48–72 h — a bridge only, while the antiresorptive takes hold.',
      'Durable antiresorptive AFTER hydration: zoledronic acid 4 mg IV over ≥15 min (onset 24–72 h, nadir 4–7 d, lasts 2–4 wk; renal-caution eGFR <60) or pamidronate 60–90 mg IV over 2–24 h (60 mg if Ca <13.5).',
      'Denosumab 60–120 mg SC (120 mg typical for malignancy; may repeat days 8, 15, 29 for refractory disease): the 2023 Endocrine Society suggests it OVER IV bisphosphonate for acute hypercalcemia of malignancy (conditional), and it is the drug of choice with eGFR <30/dialysis (no renal adjustment) — pre-replete vitamin D and watch for rebound hypocalcemia, especially in CKD.',
      'Cinacalcet 30 mg PO BID (titrate q2–4 wk) for parathyroid carcinoma or inoperable PHPT crisis — not a bridge for other etiologies.',
      'Glucocorticoids (hydrocortisone 200–300 mg/day IV ×3–5 d, or prednisone 40–60 mg/day) ONLY for calcitriol-mediated disease — lymphoma, granulomatous, vitamin D toxicity.',
      'Hemodialysis with a low-/zero-calcium bath for life-threatening hypercalcemia with AKI/ESRD, heart failure precluding hydration, or refractory cases.',
      'Loop diuretics are NOT routine — reserve furosemide for volume overload AFTER euvolemia is restored (2023 Endocrine Society: very little supporting evidence).',
      'Definitive: urgent parathyroidectomy after medical stabilization for PHPT crisis (5th International Workshop — an explicit surgical indication; experienced surgeon, >50 PTX/yr); oncologic therapy for malignancy.',
    ],
    followUp: [
      'ICU/stepdown with telemetry for Ca >14 mg/dL or symptomatic; serial Ca q6–12h initially then daily; Mg, phosphate, creatinine q12–24h; strict I&O.',
      'Floor is appropriate for moderate, asymptomatic, responding patients.',
      'Prevent post-antiresorptive hypocalcemia: replete vitamin D (and Mg) first, and monitor Ca for WEEKS after denosumab — rebound hypocalcemia is real, especially in CKD.',
      'Definitive treatment of the cause: parathyroidectomy for PHPT; oncologic therapy for malignancy.',
    ],
    pearls: [
      'Zoledronic acid before volume repletion → AKI. Always hydrate first; never bisphosphonate into a dry patient.',
      'Furosemide while still hypovolemic worsens prerenal failure and hypercalcemia — fluids, not loops.',
      'Calcitonin buys hours while the antiresorptive (days) takes effect — start both together in severe disease.',
      'Denosumab is the go-to when bisphosphonates fail or renal function is poor — but it has no renal off-switch; respect the rebound hypocalcemia.',
      'Diluting corrected-Ca decisions in CKD/ICU patients — use ionized calcium.',
      'Check PTH before discharge even if malignancy is obvious — concurrent PHPT is common and changes management.',
    ],
    tables: [
      {
        title: 'Severity bands (Endocrine Society 2023, hypercalcemia of malignancy)',
        columns: ['Band', 'Total calcium (mg/dL)', 'mmol/L'],
        rows: [
          ['Mild', '10.5 to <12.0', '2.6 to <3.0'],
          ['Moderate', '12.0–14.0', '3.0–3.5'],
          ['Severe', '>14.0', '>3.5'],
        ],
        note: 'Crisis = severe hypercalcemia plus organ dysfunction (altered mental status, AKI, arrhythmia, volume depletion); symptoms track the rate of rise as much as the number.',
      },
      {
        title: 'Lowering agents — onset, duration, dose',
        columns: ['Agent', 'Onset', 'Duration', 'Dose / notes'],
        rows: [
          ['IV isotonic saline', 'Immediate', 'While running', '1–2 L bolus, then 200–500 mL/h to UOP 100–150 mL/h'],
          ['Calcitonin', '2–4 h', 'Tachyphylaxis by 48–72 h', '4 IU/kg SC/IM q12h (up to 6–8 IU/kg q6–12h); severe/symptomatic'],
          ['Zoledronic acid', '24–72 h', 'Nadir 4–7 d; 2–4 wk', '4 mg IV over ≥15 min, AFTER repletion; caution eGFR <60'],
          ['Pamidronate', '2–4 days', 'Weeks', '60–90 mg IV over 2–24 h (60 mg if Ca <13.5)'],
          ['Denosumab', 'Days', 'Weeks', '60–120 mg SC; suggested over IV bisphosphonate in HCM (2023); agent of choice eGFR <30/dialysis'],
          ['Cinacalcet', 'Days', 'While on drug', '30 mg PO BID; parathyroid carcinoma / inoperable PHPT'],
          ['Glucocorticoid (calcitriol-mediated)', '2–5 days', 'Variable', 'Hydrocortisone 200–300 mg/day IV ×3–5 d, or prednisone 40–60 mg/day'],
          ['Hemodialysis', 'Immediate', '—', 'Low-/zero-calcium bath; AKI/ESRD, CHF precluding hydration, refractory'],
        ],
        note: 'Combine immediate therapy (saline + calcitonin) with durable therapy (bisphosphonate or denosumab); calcitonin covers the gap until the antiresorptive works. Urgent parathyroidectomy after stabilization for PHPT crisis.',
      },
    ],
    references: [
      {
        label: 'Treatment of Hypercalcemia of Malignancy in Adults: An Endocrine Society Clinical Practice Guideline',
        source: 'Endocrine Society — J Clin Endocrinol Metab 108(3):507–528',
        year: '2023',
        url: 'https://pubmed.ncbi.nlm.nih.gov/36545746/',
      },
      {
        label: 'Evaluation and Management of Primary Hyperparathyroidism: Summary Statement and Guidelines from the Fifth International Workshop',
        source: 'International Workshop on Primary Hyperparathyroidism (Bilezikian JP et al) — J Bone Miner Res 37(11):2293–2314',
        year: '2022',
        url: 'https://pubmed.ncbi.nlm.nih.gov/36245251/',
      },
      {
        label: 'Hypercalcemia: A Review',
        source: 'Walker MD, Shane E — JAMA 328(16):1624–1636',
        year: '2022',
        url: 'https://jamanetwork.com/journals/jama/fullarticle/2797565',
      },
      {
        label: 'Endocrine Emergency Guidance: Emergency management of acute hypercalcaemia in adult patients',
        source: 'Society for Endocrinology (Walsh J, Gittoes N, Selby P) — Endocr Connect 5(5):G9–G11',
        year: '2016',
        url: 'https://doi.org/10.1530/EC-16-0055',
      },
    ],
    lastReviewed: '2026-08',
  },
  {
    id: 'hypocalcemia',
    name: 'Severe / Symptomatic Hypocalcemia',
    category: 'calcium',
    summary: 'Acute hypocalcemia causing neuromuscular irritability that can escalate to tetany, laryngospasm, seizures, and QT prolongation — most often after thyroid or parathyroid surgery. Symptoms track the rate of fall and the ionized Ca, and magnesium must be normal or repletion fails.',
    firstActions: [
      'Cardiac monitor + ECG (QTc); confirm with IONIZED calcium — symptoms (tetany, seizure, laryngospasm, arrhythmia) mandate IV calcium NOW, whatever the total Ca shows.',
      'Symptomatic/severe: calcium GLUCONATE 10% 1–2 g (10–20 mL) IV over 10–20 min, diluted in 50–100 mL D5W or NS; repeat q10–60 min until symptoms resolve. Calcium CHLORIDE (1 g over 5–10 min) is CENTRAL-LINE ONLY — arrest/peri-arrest.',
      'Draw before/while treating: ionized Ca, Mg, phosphate, PTH, creatinine, 25-OHD.',
      'Replete Mg concurrently: MgSO4 2 g IV over 10–15 min if severe, then an infusion (or 4–5 g IM), target Mg ≥0.8 mmol/L — hypocalcemia is REFRACTORY until Mg is corrected.',
      'If symptoms recur, start a maintenance infusion: ~10 g calcium gluconate in 1 L NS/D5W at 50–100 mL/h (≈0.5–1.5 mg/kg/h elemental Ca), titrated to ionized Ca ~1.0–1.15 mmol/L with q4–6h checks.',
    ],
    features: [
      'Perioral and acral (fingertip and toe) paresthesias — the earliest symptom.',
      'Chvostek sign (facial twitch on tapping the facial nerve) and Trousseau sign (carpopedal spasm with a BP cuff above systolic ×3 min — the more specific of the two).',
      'Muscle cramps and tetany; laryngospasm and bronchospasm (life-threatening); seizures.',
      'Cardiac: prolonged QTc, arrhythmia, hypotension, and reduced contractility or heart failure.',
      'Hypocalcemic crisis typically at ionized Ca ≤0.7–0.8 mmol/L — but severity depends on the rate of fall and the ionized fraction, not the total Ca.',
    ],
    diagnosis: [
      'Confirm with IONIZED calcium; use corrected Ca only when albumin is reliable (total Ca reads falsely low with hypoalbuminemia, and alkalosis drops the ionized fraction at any total).',
      'Bands: mild ionized 1.0–1.2 mmol/L; moderate–severe <1.0 mmol/L; severe symptomatic = any level with tetany, seizure, laryngospasm, or arrhythmia.',
      'Check MAGNESIUM — hypomagnesemia impairs PTH secretion AND end-organ action and causes refractory hypocalcemia. Also phosphate, PTH, 25-OHD, creatinine: LOW PTH = hypoparathyroidism; HIGH PTH = secondary response (vitamin D deficiency, CKD, pseudohypoparathyroidism).',
      'Post-thyroid/parathyroid surgery: watch for HUNGRY BONE syndrome — profound, prolonged calcium requirements after parathyroidectomy.',
      'Common causes: post-surgical hypoparathyroidism, hungry bone syndrome, severe vitamin D deficiency, CKD, acute pancreatitis, hyperphosphatemia or tumor lysis, and drugs (bisphosphonates, denosumab, cinacalcet).',
      'ECG for QT prolongation.',
    ],
    management: [
      'Symptomatic or severe (tetany, laryngospasm, seizure, QTc prolongation): calcium gluconate 10% 1–2 g (10–20 mL; 1 g = 93 mg elemental Ca) IV over 10–20 min in 50–100 mL D5W or NS on a cardiac monitor; repeat q10–60 min until symptoms resolve. Avoid the same line as bicarbonate or phosphate (precipitates).',
      'Calcium chloride 10% 1 g (10 mL) over 5–10 min only for arrest/peri-arrest — CENTRAL LINE ONLY (3× the elemental Ca of gluconate, 272 mg/g; extravasation → tissue necrosis).',
      'Maintenance infusion if needed: ~10 g calcium gluconate (10 ampoules) in 1 L NS/D5W at 50–100 mL/h (≈0.5–1.5 mg/kg/h elemental), titrated to ionized Ca ~1.0–1.15 mmol/L (low-normal); recheck q4–6h.',
      'Replete MAGNESIUM first or concurrently when low: MgSO4 2 g IV over 10–15 min (severe) then infusion, or 4–5 g IM; target Mg ≥0.8 mmol/L; caution in renal failure.',
      'Transition to enteral for hypoparathyroidism: calcitriol 0.25–0.5 mcg PO BID (fast onset) + calcium carbonate 1–3 g/day elemental in divided doses with meals — active vitamin D + calcium is the standard of care (2022 International Workshop); add a thiazide + low-salt diet if hypercalciuria.',
      'Replete vitamin D deficiency (e.g., cholecalciferol 50,000 IU/wk × 6–8 wk, then maintenance; keep 25-OHD >20–30 ng/mL).',
      'Chronic refractory hypoparathyroidism: PTH replacement is specialist-initiated — rhPTH(1-84) (Natpara) was withdrawn in the US at the end of 2024, so flag availability; teriparatide is an off-label alternative in some centers.',
      'Digoxin-treated patients: IV calcium may potentiate arrhythmia — infuse slowly with monitoring. Ceftriaxone is incompatible in the same line (flush between).',
    ],
    followUp: [
      'Telemetry during IV repletion (bradycardia, arrhythmia); ionized Ca q1–4h on an infusion, q4–6h intermittent; Mg q12–24h.',
      'ICU for seizures, laryngospasm, heart failure, or need for continuous infusion; post-op neck-surgery patients need a prolonged wean — convert to PO calcium + calcitriol before discharge.',
      'Target LOW-NORMAL calcium in chronic hypoparathyroidism — with no PTH brake on renal calcium excretion, overcorrection causes hypercalciuria, nephrocalcinosis, and CKD.',
      'Endocrine follow-up for long-term hypoparathyroidism management.',
    ],
    pearls: [
      'Replete magnesium or repletion fails — it is the most common cause of "refractory" hypocalcemia.',
      'Calcium GLUCONATE peripherally; calcium CHLORIDE delivers 3× the elemental calcium but is sclerosing and causes severe necrosis on extravasation — central line only.',
      'Symptomatic patients get IV calcium, not oral boluses — oral calcium is for the asymptomatic and for maintenance.',
      'Trousseau sign is more specific than Chvostek (which can be positive in healthy people).',
      'After total thyroidectomy, watch for symptomatic hypocalcemia at 24–72 h; a falling or low post-op PTH predicts it.',
      'Co-infusing calcium with bicarbonate, phosphate, or ceftriaxone precipitates — flush between.',
    ],
    tables: [
      {
        title: 'Calcium gluconate vs calcium chloride',
        columns: ['Feature', 'Calcium gluconate 10%', 'Calcium chloride 10%'],
        rows: [
          ['Elemental Ca per 10 mL (1 g)', '~93 mg', '~272 mg (3× gluconate)'],
          ['Access', 'Peripheral acceptable', 'CENTRAL line only'],
          ['Extravasation risk', 'Lower', 'High — tissue necrosis'],
          ['Typical use', 'First line for repletion', 'Arrest / peri-arrest, central access'],
        ],
        note: 'Most non-arrest hypocalcemia is treated with calcium gluconate; chloride is reserved for arrest or central-access situations because of its sclerosing risk.',
      },
      {
        title: 'Acute repletion protocol by situation',
        columns: ['Situation', 'Agent', 'Dose / protocol'],
        rows: [
          ['Severe symptomatic (tetany, seizure, laryngospasm, QTc↑)', 'Calcium gluconate 10%', '1–2 g (10–20 mL) IV over 10–20 min in 50–100 mL D5W/NS; repeat q10–60 min'],
          ['Arrest / peri-arrest', 'Calcium chloride 10%', '1 g (10 mL) IV over 5–10 min — CENTRAL only'],
          ['Maintenance', 'Calcium gluconate infusion', '~10 g in 1 L at 50–100 mL/h; titrate to ionized Ca 1.0–1.15 mmol/L'],
          ['Hypomagnesemia (mandatory co-repletion)', 'Magnesium sulfate', '2 g IV over 10–15 min, then infusion or 4–5 g IM; target Mg ≥0.8 mmol/L'],
          ['Transition to enteral (hypoparathyroidism)', 'Calcitriol + oral calcium', 'Calcitriol 0.25–0.5 mcg PO BID + calcium carbonate 1–3 g/day elemental'],
        ],
        note: 'On a cardiac monitor throughout. In chronic hypoparathyroidism target low-normal Ca to avoid hypercalciuria and nephrocalcinosis — there is no PTH brake on renal calcium excretion.',
      },
    ],
    references: [
      {
        label: 'Endocrine Emergency Guidance: Emergency management of acute hypocalcaemia in adult patients',
        source: 'Society for Endocrinology (Turner J, Gittoes N, Selby P) — Endocr Connect 5(5):G7–G8',
        year: '2016',
        url: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5314808/',
      },
      {
        label: 'Evaluation and Management of Hypoparathyroidism: Summary Statement and Guidelines from the Second International Workshop',
        source: 'Khan AA, Bilezikian JP, Brandi ML et al — J Bone Miner Res 37(12):2568–2585',
        year: '2022',
        url: 'https://pubmed.ncbi.nlm.nih.gov/36054621/',
      },
      {
        label: 'Hypoparathyroidism: diagnosis, management and emerging therapies',
        source: 'Khan S, Khan AA — Nat Rev Endocrinol 21(6):360–374',
        year: '2025',
        url: 'https://pubmed.ncbi.nlm.nih.gov/39905273/',
      },
      {
        label: 'American Thyroid Association Statement on Postoperative Hypoparathyroidism',
        source: 'Orloff LA et al — Thyroid 28(7):830–841',
        year: '2018',
        url: 'https://doi.org/10.1089/thy.2017.0309',
      },
    ],
    lastReviewed: '2026-08',
  },

  // ───────────────────────────── SODIUM ─────────────────────────────
  {
    id: 'hyponatremia',
    name: 'Severe Hyponatremia',
    category: 'sodium',
    summary: 'Low serum sodium — management turns on two axes: the SYMPTOMS and acuity (cerebral-edema risk when acute and severe) and the CORRECTION RATE (osmotic demyelination risk when a chronic low sodium is raised too fast). Diagnose by tonicity, then volume status and urine studies; the 2014 European guideline and 2013 US expert panel remain the anchor documents.',
    firstActions: [
      'Assess SYMPTOMS and chronicity first — severe symptoms (seizure, coma, obtundation, cardiorespiratory distress) mean 3% saline NOW regardless of the number or the cause; simultaneously confirm true hypotonic hyponatremia (serum osm <275 mOsm/kg).',
      'Severe symptoms: 3% NaCl 150 mL IV over 20 min → recheck Na → repeat ×2–3 as needed until Na rises 4–6 mEq/L or symptoms abate (US panel alternative: 100 mL bolus over 10 min, up to 3 total). A small, rapid 4–6 mEq/L rise reverses cerebral edema — then STOP aggressive correction.',
      'Send paired urine osm + urine Na, TSH, and morning cortisol (exclude hypothyroidism and glucocorticoid deficiency BEFORE labeling SIADH); correct Na for hyperglycemia (+1.6–2.4 mEq/L per 100 mg/dL above 100; use 2.4 at glucose >400).',
      'Set the correction cap at the outset: ≤8–10 mEq/L per 24 h standard; ≤4–6 (hard cap 8) if high ODS risk — Na ≤105, alcoholism, malnutrition, hypokalemia, cirrhosis/advanced liver disease. Na checks q2–4h during active correction.',
      'Have desmopressin ready for overcorrection or anticipated autocorrection: DDAVP 2–4 mcg IV/SC q6–8h ± D5W 3 mL/kg/h; a 2024 RCT supports a PROACTIVE "DDAVP clamp" from treatment start in severe symptomatic hyponatremia to prevent overshoot.',
    ],
    features: [
      'Symptoms track severity and rate: nausea, headache, lethargy, confusion → seizures, coma, respiratory arrest (acute cerebral edema, typically Na <120 or a rapid drop).',
      'Severity bands: mild 130–134, moderate 125–129, severe <125, profound ≤120 mEq/L — but symptom severity, not the number alone, drives urgency.',
      'Chronic hyponatremia is often paucisymptomatic but still causes gait instability, falls, and attention deficits even when called "asymptomatic."',
      'Moderate symptoms: vomiting, confusion, gait instability; mild/absent: nausea, headache, subtle cognitive change.',
    ],
    diagnosis: [
      'Step 1 — measure serum OSMOLALITY. Most hyponatremia is hypotonic (true). Exclude isotonic pseudohyponatremia (severe hypertriglyceridemia or paraproteinemia — lab-dependent) and hypertonic hyponatremia (hyperglycemia, mannitol).',
      'Step 2 — for hypotonic hyponatremia, assess VOLUME STATUS and send urine osmolality and urine sodium.',
      'SIADH criteria: hypotonic hyponatremia + clinical euvolemia + urine osm >100 mOsm/kg + urine Na >30 mEq/L (on normal salt/water intake; some use >40) + normal renal function + EXCLUSION of hypothyroidism and glucocorticoid deficiency (TSH and morning cortisol are mandatory). Supportive: low uric acid (<4 mg/dL), FE-urate >12%, low BUN.',
      'Urine osm <100 mOsm/kg → appropriately dilute urine: primary polydipsia, beer potomania, low solute intake.',
      'Distinguish SIADH from cerebral salt wasting (volume-DEPLETED neuro patients) and reset osmostat; hypovolemic (urine Na <20–30 extrarenal, >30 renal/diuretic) vs hypervolemic (heart failure, cirrhosis, nephrotic — urine Na usually <20).',
      'Decide ACUTE (<48 h — post-op, MDMA, exercise, polydipsia; tolerates faster correction) vs CHRONIC or unknown (ODS risk — correct slowly).',
      '2024–25 status note: no replacement hyponatremia guideline as of early 2026; a 2024–25 ESE survey documents wide practice variation and calls for an evidence-based revision — guideline update anticipated.',
    ],
    management: [
      'Severe symptoms, any chronicity: 3% NaCl 150 mL IV over 20 min, recheck Na, repeat ×2–3 until Na rises 4–6 mEq/L or symptoms abate — the risk of untreated brain edema far exceeds the ODS risk in this window; do not chase the number.',
      'Moderate symptoms: 3% saline infusion ~0.5–2 mL/kg/h with Na checks q2–4h — same total correction caps apply.',
      'CORRECTION CAPS: ≤8–10 mEq/L per 24 h standard; ≤4–6 (hard cap 8) if high ODS risk; also ≤18 mEq/L per 48 h (US panel). Exceeding the cap = treat as overcorrection.',
      'OVERCORRECTION (or anticipated overcorrection from autocorrection/aquaresis): stop all hypertonic/isotonic fluids; re-lower with desmopressin 2–4 mcg IV/SC q6–8h ± D5W 3 mL/kg/h to bring Na back under the cap. The proactive DDAVP clamp at treatment start is RCT-supported (2024) for severe symptomatic cases.',
      'Hypovolemic: 0.9% NaCl to restore volume — once volume-replete, AVP falls and a free-water diuresis can trigger RAPID AUTOCORRECTION; hold desmopressin ready.',
      'Hypervolemic (CHF/cirrhosis): fluid + salt restriction and a loop diuretic; hypertonic saline only for severe symptoms, combined with the loop.',
      'Chronic SIADH, first line: fluid restriction 800–1,000 mL/day (all fluids) — predictors of failure: urine osm >500, urine (Na+K) > serum Na, <1.5 mEq/L rise after 24–48 h on 1 L restriction.',
      'Chronic SIADH, second line: oral urea 15–30 g/day (osmotic diuresis — cheap, effective, guideline-endorsed), or NaCl tablets + loop diuretic, plus increased solute (protein) intake; demeclocycline and lithium are discouraged (European).',
      'Tolvaptan (V2 antagonist), refractory cases only: start 15 mg PO once daily INPATIENT ONLY, with NO fluid restriction for the first 24 h and Na checks q6–8h. Cautions: overcorrection/ODS (especially Na <120, hypokalemia, alcoholism), hepatotoxicity (avoid >30 days and liver disease), thirst/dehydration. The US panel reserves it for refractory euvolemic/hypervolemic cases; the European guideline does not recommend vaptans.',
    ],
    followUp: [
      'Severe symptoms or 3% saline running → ICU/stepdown with Na checks q2–4h during active correction, then q4–6h; daily weights, strict I&O. Floor for asymptomatic moderate hyponatremia on fluid restriction.',
      'SIADH etiology workup: chest imaging/malignancy screen, CNS disease, drugs (SSRIs, anticonvulsants, antipsychotics, NSAIDs, opiates, chemotherapy), pulmonary disease, nausea/pain/post-op state.',
      'Watch for delayed ODS 2–7 days after overcorrection (dysarthria, dysphagia, quadriparesis, locked-in, behavioral change).',
    ],
    pearls: [
      'The danger is the RATE, in both directions — too fast down risks cerebral edema; too fast up risks osmotic demyelination.',
      '2023–25 data: overcorrection is COMMON (18–41% of severe cases) but ODS is RARE (0.05–0.5%) — the caps remain standard of care, and under-treating symptomatic acute hyponatremia out of ODS fear is the bigger mistake.',
      'Isotonic saline can WORSEN SIADH when urine osm >530 or urine (Na+K) exceeds serum Na — do not reflexively run NS.',
      'Miss hypovolemic autocorrection and post-obstructive/desmopressin-washout aquaresis and the Na overshoots — have DDAVP ready.',
      'Never label SIADH without excluding adrenal insufficiency and hypothyroidism.',
      'Tolvaptan: outpatient initiation, fluid restriction in the first 24 h, or use beyond 30 days → harm.',
    ],
    tables: [
      {
        title: 'Severity bands and symptom tiers',
        columns: ['Band', 'Serum Na (mEq/L)', 'Symptom-driven action'],
        rows: [
          ['Mild', '130–134', 'Cause-directed; fluid restriction if SIADH'],
          ['Moderate', '125–129', 'Moderate symptoms (confusion, vomiting, gait instability) → 3% infusion 0.5–2 mL/kg/h'],
          ['Severe', '<125', 'Severe symptoms (seizure, coma) → 3% 150 mL bolus over 20 min, repeat ×2–3'],
          ['Profound', '≤120', 'As severe; highest urgency; ICU'],
        ],
        note: 'Symptom severity, not the number alone, drives the decision to give hypertonic saline; chronic/unknown-duration cases carry the demyelination risk.',
      },
      {
        title: 'Classifying hypotonic hyponatremia',
        columns: ['Volume status', 'Urine Na', 'Typical causes', 'First-line treatment'],
        rows: [
          ['Hypovolemic', '<20–30 (extrarenal); >30 (renal/diuretic)', 'GI/skin loss, diuretics, cerebral salt wasting, adrenal insufficiency', 'Isotonic saline — watch for rapid autocorrection'],
          ['Euvolemic', '>30, urine osm >100', 'SIADH, hypothyroidism, glucocorticoid deficiency, reset osmostat', 'Fluid restriction 800–1,000 mL/d; treat cause'],
          ['Euvolemic, dilute urine', 'Variable, urine osm <100', 'Primary polydipsia, beer potomania, low solute', 'Increase solute intake; restrict water'],
          ['Hypervolemic', '<20 (>30 in renal failure)', 'Heart failure, cirrhosis, nephrotic, renal failure', 'Fluid + Na restriction, loop diuretic; treat cause'],
        ],
        note: 'Exclude hyperglycemia and pseudohyponatremia first, and check TSH and cortisol before diagnosing SIADH.',
      },
      {
        title: 'Correction caps and overcorrection rescue',
        columns: ['Scenario', 'Protocol'],
        rows: [
          ['Standard 24-h cap', '≤8–10 mEq/L per 24 h (also ≤18 mEq/L per 48 h, US panel)'],
          ['High ODS risk (Na ≤105, alcoholism, malnutrition, hypokalemia, cirrhosis)', '≤4–6 mEq/L per 24 h (hard cap 8)'],
          ['Overcorrection / anticipated autocorrection', 'Stop all hypertonic/isotonic fluids; DDAVP 2–4 mcg IV/SC q6–8h ± D5W 3 mL/kg/h to re-lower under the cap'],
          ['Proactive prevention (severe symptomatic)', 'DDAVP clamp from treatment start — RCT-supported (2024) to prevent overshoot'],
        ],
        note: 'A small 4–6 mEq/L rise relieves cerebral edema; everything beyond that is risk without benefit.',
      },
    ],
    references: [
      {
        label: 'Clinical practice guideline on diagnosis and treatment of hyponatraemia',
        source: 'ERA-EDTA/ESE/ESICM (Spasovski G et al) — Nephrol Dial Transplant 29(Suppl 2):i1–i39',
        year: '2014',
        url: 'https://pubmed.ncbi.nlm.nih.gov/24569496/',
      },
      {
        label: 'Diagnosis, evaluation, and treatment of hyponatremia: expert panel recommendations',
        source: 'US Expert Panel (Verbalis JG et al) — Am J Med 126(10 Suppl 1):S1–S42',
        year: '2013',
        url: 'https://pubmed.ncbi.nlm.nih.gov/24074529/',
      },
      {
        label: 'Diagnosis and treatment of hyponatremia: compilation of the guidelines',
        source: 'Hoorn EJ, Zietse R — J Am Soc Nephrol 28(5):1340–1349',
        year: '2017',
        url: 'https://doi.org/10.1681/ASN.2016101139',
      },
      {
        label: 'Safety and efficacy of proactive versus reactive administration of desmopressin in severe symptomatic hyponatremia: a randomized controlled trial',
        source: 'Baek SH et al — Sci Rep 14:7396',
        year: '2024',
        url: 'https://www.nature.com/articles/s41598-024-57657-z',
      },
    ],
    lastReviewed: '2026-08',
  },
  {
    id: 'hypernatremia',
    name: 'Severe Hypernatremia',
    category: 'sodium',
    summary: 'High serum sodium always means a water deficit relative to sodium — usually impaired thirst or no access to water (the very young, elderly, or obtunded), sometimes diabetes insipidus or osmotic losses; rarely sodium overload. Correct chronic cases slowly to avoid cerebral edema.',
    firstActions: [
      'Assess perfusion first: shock or hypoperfusion → 0.9% NaCl FIRST until hemodynamically stable — even in hypernatremia; volume before free water.',
      'Calculate the free-water deficit: FWD (L) = TBW × [(measured Na ÷ 140) − 1]; TBW = 0.6 × kg (men), 0.5 (women), ~0.5/0.45 in elderly men/women. Example: 60-kg woman, Na 155 → 30 L × (155/140 − 1) ≈ 3.2 L.',
      'Decide chronicity: chronic or unknown duration → ≤0.5 mEq/L/h and ≤10–12 mEq/L per 24 h; acute (<48 h, e.g., salt load, post-op DI) may correct ~1 mEq/L/h — the brain has not yet adapted.',
      'Start replacement: enteral free water preferred, or IV D5W / 0.45% NaCl; replace ~half the deficit in the first 24 h, the rest over 48–72 h — and ADD ongoing losses (urine, GI, insensible).',
      'Send urine osmolality and track hourly urine output: an inappropriately dilute urine with hypernatremia = DI (see the AVP deficiency entry) — Na rechecks q2–4h during active correction.',
    ],
    features: [
      'Thirst is the main defense — its absence (impaired access, altered mentation, hypodipsia/adipsia) is what lets hypernatremia develop.',
      'Neurologic: lethargy, irritability, weakness, hyperreflexia, twitching, seizures, coma; severity tracks the rate of rise (rapid in acute; the brain accumulates idiogenic osmoles in chronic).',
      'Clues to the cause: volume depletion (GI losses, osmotic diuresis), a large dilute urine output (diabetes insipidus), or fever and tachypnea (insensible losses).',
      'Rare sodium-overload etiologies: hypertonic saline administration, salt poisoning, hyperaldosteronism.',
    ],
    diagnosis: [
      'Serum sodium with the FREE-WATER DEFICIT (formula above) — and a volume-status exam.',
      'Severity bands: mild 146–150, moderate 151–159, severe ≥160 mEq/L.',
      'URINE OSMOLALITY: high (>700–800, low volume) = appropriate renal water conservation (extrarenal/insensible loss, low intake); inappropriately dilute (osm below serum, large volume) = diabetes insipidus or osmotic diuresis (glucose, mannitol, urea).',
      'Chronic (>48 h or unknown) vs acute — determines the safe correction speed.',
      'For dilute urine, desmopressin testing separates AVP deficiency (central DI) from AVP resistance (nephrogenic DI) — see the diabetes insipidus entry for copeptin-based diagnosis.',
    ],
    management: [
      'Hypovolemic/unstable: isotonic saline FIRST until hemodynamically stable, then turn to the water deficit.',
      'Replace the free-water deficit with oral/enteral water when possible, or IV D5W or 0.45% saline; ADD ongoing losses to the calculated deficit — replace ~half in 24 h, the remainder over 48–72 h.',
      'RATE LIMITS (chronic/unknown): ≤0.5 mEq/L/h and ≤10–12 mEq/L per 24 h — faster correction risks cerebral edema because the brain has accumulated idiogenic osmoles. Acute (<48 h) may be corrected ~1 mEq/L/h.',
      '2023 evidence flag: a large adult cohort (JAMA Netw Open 2023) found faster correction associated with LOWER mortality and no neurologic harm, questioning the pediatric-derived ≤0.5 mEq/L/h dogma — still follow the traditional limits pending guideline revision, and document your rationale if deviating.',
      'Sodium overload (rare): D5W + loop diuretic; dialysis if renal failure.',
      'Treat the cause: AVP deficiency → desmopressin; AVP resistance → stop the offending drug (lithium), correct hypercalcemia/hypokalemia, thiazide + low-solute diet; osmotic diuresis → control the osmole (e.g., glucose).',
    ],
    followUp: [
      'Na q2–4h during active correction, then q6h; hourly urine output if DI is suspected.',
      'ICU for Na ≥160, altered mental status, or when rapid correction is needed; floor for mild cases with intact thirst and enteral replacement.',
      'Diagnose and manage diabetes insipidus or the source of losses; ensure ongoing access to water — hospital-acquired hypernatremia is usually iatrogenic in patients who cannot ask for water.',
    ],
    pearls: [
      'Always account for ONGOING free-water losses in the deficit calculation — under-replacing them is the usual reason the sodium does not fall.',
      'Isotonic fluids alone cannot correct established hypernatremia — they provide no free water (or worsen it).',
      'Seizures DURING correction = cerebral edema from over-rapid correction — pause hypotonic fluids.',
      'In DI patients, withholding desmopressin while giving large hypotonic volumes produces wild Na swings (see the AVP deficiency entry).',
      'Resuscitate volume before chasing the sodium in a shocked patient.',
    ],
    tables: [
      {
        title: 'Free-water deficit and correction rates',
        columns: ['Item', 'Protocol'],
        rows: [
          ['Free-water deficit', 'FWD (L) = TBW × [(Na ÷ 140) − 1]; TBW = 0.6 × kg men, 0.5 women, ~0.5/0.45 elderly'],
          ['Shock / hypoperfusion', '0.9% NaCl first until stable — even in hypernatremia'],
          ['Chronic or unknown duration', '≤0.5 mEq/L/h and ≤10–12 mEq/L per 24 h; ~half the deficit in 24 h, rest over 48–72 h'],
          ['Acute (<48 h)', 'May correct ~1 mEq/L/h — brain not yet adapted'],
          ['Sodium overload (rare)', 'D5W + loop diuretic; dialysis if renal failure'],
        ],
        note: 'A 2023 JAMA Netw Open adult cohort found faster correction was not associated with neurologic harm and was associated with lower mortality — evolving evidence; traditional limits remain standard of care.',
      },
      {
        title: 'Urine osmolality in hypernatremia',
        columns: ['Urine osm (mOsm/kg)', 'Interpretation', 'Examples'],
        rows: [
          ['>700–800 (concentrated)', 'Appropriate renal water conservation', 'Insensible/GI loss, low water intake'],
          ['300–700 (intermediate)', 'Partial concentrating defect / osmotic', 'Osmotic diuresis, partial DI'],
          ['<300 (dilute, vs high serum)', 'Inappropriate — diabetes insipidus', 'AVP deficiency or AVP resistance'],
        ],
        note: 'An osmotic diuresis (glucose, mannitol, urea from high-protein feeds) also raises urine output — check a urine glucose and the clinical context before labeling it DI.',
      },
    ],
    references: [
      {
        label: 'Diagnosis and Management of Sodium Disorders: Hyponatremia and Hypernatremia',
        source: 'Miller NE, Rushlow D, Stacey SK — Am Fam Physician 108(5):476–486',
        year: '2023',
        url: 'https://www.aafp.org/pubs/afp/issues/2023/1100/diagnosis-management-sodium-disorders-hyponatremia-hypernatremia.html',
      },
      {
        label: 'Rate of Correction and All-Cause Mortality in Patients With Severe Hypernatremia',
        source: 'Feigin E et al — JAMA Netw Open 6(9):e2334355',
        year: '2023',
        url: 'https://jamanetwork.com/journals/jamanetworkopen/fullarticle/2809955',
      },
      {
        label: 'Hypernatremia (StatPearls)',
        source: 'Sonani B et al — NCBI Bookshelf',
        year: '2023',
        url: 'https://www.ncbi.nlm.nih.gov/books/NBK441960/',
      },
    ],
    lastReviewed: '2026-08',
  },

  // ─────────────────────────── POTASSIUM ───────────────────────────
  {
    id: 'hyperkalemia',
    name: 'Hyperkalemia',
    category: 'potassium',
    summary: 'Elevated serum potassium with a real risk of fatal arrhythmia — per the 2023 UK Kidney Association guideline, the priority is to STABILIZE the myocardium (calcium), SHIFT potassium into cells (insulin-glucose ± salbutamol), then REMOVE it from the body (binders, diuretics, dialysis). Endocrine causes (hypoaldosteronism, adrenal insufficiency, type 4 RTA) are easy to miss.',
    firstActions: [
      'ECG immediately — mandatory for K ≥6.0, continuous cardiac monitoring for ECG changes or K ≥6.5 (UKKA). The ECG is the severity arbiter, but a normal ECG does NOT exclude danger at very high K.',
      'ECG changes present: calcium GLUCONATE 10% 30 mL IV over 10 min FIRST (UKKA 2023 standard after the MHRA safety alert; =6.8 mmol Ca); repeat after 5–10 min if changes persist/recur. It protects the heart in 1–3 min and lasts 30–60 min — it lowers NOTHING. (Arrest/peri-arrest: calcium chloride 10% 10 mL over 5 min, central preferred.)',
      'Shift K into cells: regular (soluble) insulin 10 units IV + 25 g glucose (50 mL of 50% dextrose) over 5–15 min; consider 5 units in ESRD. If pre-treatment glucose <7 mmol/L (126 mg/dL), follow with 10% glucose at 50 mL/h × 5 h to prevent hypoglycemia.',
      'Adjuvant: nebulized salbutamol 10–20 mg (never monotherapy — 20–40% nonresponders, and beta-blockers blunt it). Sodium bicarbonate only for severe metabolic acidosis.',
      'Remove K: sodium zirconium cyclosilicate 10 g PO TID (up to 72 h) as a bridge ± furosemide 40–80 mg IV if making urine; call renal EARLY for hemodialysis if refractory, anuric AKI/ESRD, or ongoing K release (tumor lysis, rhabdo).',
      'Stop contributors (RAASi, K-sparing diuretics, NSAIDs, TMP-SMX, heparin); confirm the lab for pseudohyperkalemia (hemolysis, thrombocytosis) — but never delay treatment for ECG changes or K ≥6.5.',
    ],
    features: [
      'Often asymptomatic until dangerous; nonspecific weakness, paresthesias, palpitations, or flaccid paralysis at high levels.',
      'ECG progression: peaked T waves → PR prolongation and flattened/absent P waves → QRS widening → sine-wave pattern → VF or asystole; also bradycardia and heart block.',
      'UKKA 2023 bands: mild 5.5–5.9, moderate 6.0–6.4, severe ≥6.5 mmol/L — or ANY K with ECG changes or symptoms.',
      'ECG changes can be ABSENT even with severe hyperkalemia, so a normal tracing is not reassuring — treat by the number and the trajectory.',
    ],
    diagnosis: [
      'Confirm the value and EXCLUDE pseudohyperkalemia (hemolyzed sample, tourniquet/fist clenching, marked thrombocytosis or leukocytosis) — recheck a free-flowing or plasma sample if the result surprises you with no ECG changes, but do not delay treatment if ECG changes or K ≥6.5.',
      'ECG mandatory for K ≥6.0; continuous monitoring for ECG changes or K ≥6.5 (UKKA).',
      'Sort the cause: reduced excretion (renal failure — the big one); drugs (ACEi/ARB, aldosterone antagonists, K-sparing diuretics, NSAIDs, trimethoprim, heparin, calcineurin inhibitors); transcellular shift (acidosis, insulin deficiency, beta-blockade, tissue breakdown — rhabdomyolysis, tumor lysis, hemolysis); and ENDOCRINE causes — hypoaldosteronism, adrenal insufficiency, and type 4 (hyporeninemic hypoaldosteronic) RTA in diabetes.',
    ],
    management: [
      'STEP 1 — Protect the heart (ECG changes): calcium gluconate 10% 30 mL IV over 10 min (UKKA 2023); may repeat after 5–10 min. US practice commonly uses 10 mL aliquots ×1–3. Never in the same line as bicarbonate. In digoxin toxicity, infuse slowly over 20–30 min diluted in 100 mL. Calcium chloride 10% 10 mL over 5 min (3× calcium content) is preferred in resuscitation; gluconate for all other settings.',
      'STEP 2 — Shift K into cells: insulin 10 units IV + 25 g glucose (onset 10–20 min, peak 30–60 min, lowers K 0.5–1.2 mmol/L, lasts 4–6 h). Monitor capillary glucose at 0, 30, 60, 90, 120, 180, 240, 300, 360, 480, and 720 min — hypoglycemia can be delayed >6 h in renal failure. Prophylactic 10% dextrose when baseline glucose <7 mmol/L.',
      'STEP 2 adjuvant: nebulized salbutamol 10–20 mg (onset ~30 min, peak 90 min, lowers K 0.5–1.0) — adjuvant only; caution in ischemic heart disease (tachycardia).',
      'STEP 2 conditional: sodium bicarbonate only for severe metabolic acidosis (50 mL of 8.4% in arrest, or 1.26% infusion titrated) — little effect without acidosis, harmful sodium load in anuria/hypervolemia, and it precipitates with calcium.',
      'STEP 3 — Remove K from the body: furosemide 40–80 mg IV if making urine and volume overloaded (adjunct); sodium zirconium cyclosilicate 10 g PO TID for up to 72 h then 5–10 g daily (onset ~1 h, lowers ~0.7–1.1 mmol/L by 24–48 h — a bridge; edema risk from sodium load; X-ray opaque); patiromer 8.4 g PO daily (onset 4–7 h — NOT for emergency monotherapy; binds Mg; separate from other oral drugs by 3 h).',
      'AVOID sodium polystyrene sulfonate acutely — slow, uncertain efficacy, intestinal necrosis risk especially with sorbitol (KDIGO 2020: prefer SZC/patiromer).',
      'STEP 3 definitive: URGENT hemodialysis for K ≥6.5 refractory to medical therapy, persistent ECG changes, anuria/AKI/ESRD, or ongoing K release (tumor lysis, rhabdo) — "shift" therapies are temporizing; plan removal early.',
      'Treat the cause: fludrocortisone for documented hypoaldosteronism; hydrocortisone if adrenal crisis is the driver; stop the offending drugs.',
    ],
    followUp: [
      'Recheck K at 1, 2, 4, 6, and 24 h after treatment of moderate/severe hyperkalemia (UKKA); telemetry until K <6.0 and stable.',
      'ICU/stepdown for severe or ECG changes; floor for mild with a reversible cause.',
      'Anticipate REBOUND hyperkalemia 4–6 h after insulin as the effect wanes — recheck, do not assume cure.',
      'Address the etiology and review the medication list; arrange definitive management (dialysis access, mineralocorticoid replacement, dietary potassium restriction) for renal or adrenal causes.',
    ],
    pearls: [
      'Calcium protects the heart but does NOT lower potassium — you still must shift it and remove it.',
      'Insulin-induced hypoglycemia is the most common serious iatrogenic harm — delayed >6 h in CKD/ESRD — so the 12-h glucose monitoring and prophylactic dextrose are not optional.',
      'Binders are not acute therapy: SZC is fastest (~1 h) but still an adjunct; patiromer is too slow for emergencies.',
      'Salbutamol as monotherapy fails (nonresponders); beta-blockers blunt it.',
      'Dialysis delays kill when medical therapy is clearly a bridge (anuric AKI).',
      'Recurrent unexplained hyperkalemia, especially in a diabetic, should prompt a look for type 4 RTA / hyporeninemic hypoaldosteronism and adrenal insufficiency.',
    ],
    tables: [
      {
        title: 'UKKA 2023 severity bands and monitoring',
        columns: ['Band', 'Serum K (mmol/L)', 'Action'],
        rows: [
          ['Mild', '5.5–5.9', 'Treat cause; review drugs; recheck'],
          ['Moderate', '6.0–6.4', 'ECG mandatory; shift ± remove; recheck K 1, 2, 4, 6, 24 h'],
          ['Severe', '≥6.5 (or any K with ECG changes/symptoms)', 'Continuous monitoring; calcium FIRST, then shift + remove; dialysis if refractory'],
        ],
        note: 'The ECG is the severity arbiter: peaked T → PR prolongation/P flattening → QRS widening → sine wave → VF/asystole — but a normal ECG does not exclude danger.',
      },
      {
        title: 'Hyperkalemia — stabilize, shift, remove (UKKA 2023)',
        columns: ['Step', 'Agent', 'Dose', 'Onset / duration'],
        rows: [
          ['Stabilize (ECG changes)', 'Calcium gluconate 10%', '30 mL IV over 10 min; repeat after 5–10 min', '1–3 min / 30–60 min'],
          ['Stabilize (arrest)', 'Calcium chloride 10%', '10 mL IV over 5 min — central preferred', '1–3 min / 30–60 min'],
          ['Shift', 'Insulin + glucose', '10 u regular IV + 25 g glucose over 5–15 min (5 u if ESRD); 10% glucose 50 mL/h × 5 h if baseline glucose <7 mmol/L', '10–20 min / 4–6 h'],
          ['Shift (adjuvant)', 'Salbutamol nebulized', '10–20 mg — adjuvant only', '~30 min / peak 90 min'],
          ['Shift (conditional)', 'Sodium bicarbonate', 'Only for severe metabolic acidosis', 'Variable'],
          ['Remove (adjunct)', 'Furosemide', '40–80 mg IV if making urine', '~30 min'],
          ['Remove (bridge)', 'Sodium zirconium cyclosilicate', '10 g PO TID ≤72 h, then 5–10 g daily', '~1 h / lowers 0.7–1.1 by 24–48 h'],
          ['Remove (too slow acutely)', 'Patiromer', '8.4 g PO daily; NOT for emergency monotherapy', '4–7 h'],
          ['Remove (definitive)', 'Hemodialysis', 'Refractory, anuric AKI/ESRD, ongoing K release', 'Immediate'],
        ],
        note: 'Calcium does not lower potassium, and shifting agents are temporary — always pair them with a removal strategy. SPS is largely abandoned acutely (intestinal necrosis risk, uncertain efficacy).',
      },
    ],
    references: [
      {
        label: 'Clinical Practice Guideline: Management of Hyperkalaemia in Adults',
        source: 'UK Kidney Association (Alfonzo A et al)',
        year: '2023',
        url: 'https://www.ukkidney.org/sites/default/files/FINAL%20VERSION%20-%20UKKA%20CLINICAL%20PRACTICE%20GUIDELINE%20-%20MANAGEMENT%20OF%20HYPERKALAEMIA%20IN%20ADULTS%20-%20191223_0.pdf',
      },
      {
        label: 'Potassium homeostasis and management of dyskalemia in kidney diseases (KDIGO Controversies Conference)',
        source: 'Clase CM et al — Kidney Int 97(1):42–61',
        year: '2020',
        url: 'https://pubmed.ncbi.nlm.nih.gov/31706619/',
      },
      {
        label: 'Hyperkalemia management in the emergency department: an expert panel consensus',
        source: 'Rafique Z et al — J Am Coll Emerg Physicians Open 2(5):e12572',
        year: '2021',
        url: 'https://doi.org/10.1002/emp2.12572',
      },
      {
        label: 'European Resuscitation Council Guidelines 2021: Cardiac arrest in special circumstances (hyperkalaemia section)',
        source: 'Lott C et al — Resuscitation 161:152–219',
        year: '2021',
        url: 'https://doi.org/10.1016/j.resuscitation.2021.02.011',
      },
    ],
    lastReviewed: '2026-08',
  },
  {
    id: 'hypokalemia',
    name: 'Hypokalemia',
    category: 'potassium',
    summary: 'Low serum potassium risking arrhythmia (especially with digoxin or a long QT) and weakness — usually GI or renal loss, a transcellular shift, or mineralocorticoid excess. Oral repletion is preferred; IV rates are capped; magnesium must be repleted or potassium will not correct.',
    firstActions: [
      'ECG + telemetry if K <2.5, symptoms, digoxin use, or significant heart disease — look for ST depression, flattened T, prominent U wave, and apparent long QT (actually QU; torsades risk).',
      'Check MAGNESIUM now — co-depleted in ~40% (diuretics, diarrhea, alcohol); K repletion is INEFFECTIVE until Mg is corrected: MgSO4 1–2 g IV over 30–60 min (2 g if severe/arrhythmia).',
      'Gut working + mild-moderate + asymptomatic: ORAL KCl 40–100 mEq/day in divided doses (20–40 mEq per dose) — oral is preferred and safer; expect ~1 mEq/L rise per 40–100 mEq with normal renal function.',
      'Severe, symptomatic, ECG changes, or NPO: IV KCl — peripheral line MAX 10 mEq/h (10 mEq in 100 mL over 1 h); central line + continuous telemetry 20 mEq/h (20 mEq in 100 mL over 1 h); 40 mEq/h only for life-threatening arrhythmia/paralysis in the ICU. NEVER IV push.',
      'Use SALINE-based diluents for rapid IV correction — dextrose-containing fluids stimulate insulin release and transiently lower K further.',
    ],
    features: [
      'Weakness, fatigue, cramps, myalgia; ileus and constipation; palpitations and arrhythmia.',
      'ECG: flattened or inverted T waves, prominent U waves, ST depression, and a prolonged QU predisposing to torsades.',
      'Severe (K <2.5): rhabdomyolysis and ascending paralysis.',
      'Rule of thumb: each 1 mmol/L fall ≈ a 200–400 mmol total-body deficit — larger when chronic.',
    ],
    diagnosis: [
      'Severity bands: mild 3.0–3.4, moderate 2.5–2.9, severe <2.5 mmol/L — or any level with symptoms or ECG changes.',
      'Serum potassium WITH magnesium and acid-base status.',
      'Distinguish a SHIFT (insulin, beta-agonists, alkalosis, thyrotoxic periodic paralysis, refeeding) from true LOSS — shift states risk rebound hyperkalemia with repletion.',
      'For true loss, check urine potassium: LOW = GI loss or prior diuretic; HIGH = ongoing renal loss — then use blood pressure and the aldosterone-to-renin ratio to screen for primary hyperaldosteronism, and consider RTA, Bartter/Gitelman, and hypomagnesemia.',
    ],
    management: [
      'Mild-moderate, asymptomatic, gut working: oral KCl 40–100 mEq/day in divided doses (20–40 mEq per dose, 2–3×/day); recheck after 2–3 days (outpatient) or the next day (inpatient).',
      'Severe, symptomatic, ECG changes, or NPO: IV KCl — peripheral ≤10 mEq/h; central + telemetry 20 mEq/h; up to 40 mEq/h only for life-threatening arrhythmia/paralysis with ICU monitoring. Recheck K 1–2 h after each 20–40 mEq and q4–6h during infusion.',
      'Concurrent hypomagnesemia: MgSO4 1–2 g IV over 30–60 min (2 g if severe/arrhythmia), may repeat, or oral Mg if mild — repletion fails without it.',
      'Transcellular shift (thyrotoxic periodic paralysis, beta-agonist): REDUCED total doses in small divided aliquots with frequent checks — give a non-selective beta-blocker (e.g., propranolol) in TPP and anticipate rebound hyperkalemia.',
      'Cardiac monitoring for severe, symptomatic, or digoxin-treated patients; reduce dose and go slower in CKD/oliguria.',
      'Treat the cause: hold or change diuretics, treat vomiting/diarrhea, address hyperaldosteronism, correct an alkalosis or shift state.',
    ],
    followUp: [
      'Telemetry for K <2.5, ECG changes, IV rates >10 mEq/h, digoxin use, or significant heart disease; floor for oral repletion of mild cases.',
      'Treat the underlying cause; adjust diuretics or add a potassium-sparing agent; ensure magnesium is repleted.',
      'Evaluate for PRIMARY HYPERALDOSTERONISM in any hypertensive or spontaneously hypokalemic patient (aldosterone-renin ratio).',
    ],
    pearls: [
      'Always check and replace magnesium — it is the most common reason hypokalemia is refractory.',
      'IV potassium in DEXTROSE-containing fluids can transiently lower K further (glucose-stimulated insulin release) — use saline diluents for rapid correction.',
      'Never give potassium by IV push — fatal arrhythmia; undiluted or too-rapid peripheral KCl causes phlebitis, pain, and necrosis.',
      'Aggressive repletion in shift-hypokalemia (insulin treatment of DKA, TPP, refeeding) overshoots into hyperkalemia — anticipate and recheck frequently.',
      'Hypokalemia plus hypertension → screen for primary hyperaldosteronism; hypokalemia plus paralysis in a young man → think thyrotoxic periodic paralysis.',
      'Not addressing the driver (diuretic dose, hyperaldosteronism, laxative abuse, Gitelman/Bartter) guarantees recurrence.',
    ],
    tables: [
      {
        title: 'Severity bands',
        columns: ['Band', 'Serum K (mmol/L)', 'Typical action'],
        rows: [
          ['Mild', '3.0–3.4', 'Oral repletion; find the cause'],
          ['Moderate', '2.5–2.9', 'Oral ± IV; ECG; check Mg'],
          ['Severe', '<2.5 (or any level with symptoms/ECG changes)', 'IV repletion with telemetry; ICU if arrhythmia/paralysis'],
        ],
        note: 'Each 1 mmol/L fall reflects roughly a 200–400 mmol total-body deficit — larger when chronic.',
      },
      {
        title: 'Potassium repletion guide',
        columns: ['Setting', 'Route / rate', 'Notes'],
        rows: [
          ['Mild–moderate, takes PO', 'Oral KCl 40–100 mEq/day divided (20–40 mEq/dose)', 'Preferred; ~1 mEq/L rise per 40–100 mEq; recheck next day (inpatient)'],
          ['Severe / symptomatic / NPO', 'IV KCl: peripheral ≤10 mEq/h; central ≤20 mEq/h with telemetry', 'Recheck K 1–2 h after each 20–40 mEq; saline diluent, NOT dextrose'],
          ['Life-threatening arrhythmia/paralysis', 'Up to 40 mEq/h', 'ICU only, continuous monitoring'],
          ['Refractory to repletion', 'Give magnesium with it', 'MgSO4 1–2 g IV over 30–60 min; low Mg drives renal K wasting'],
          ['Digoxin / arrhythmia', 'IV with cardiac monitoring', 'Hypokalemia potentiates digoxin toxicity'],
        ],
        note: 'Never give potassium by IV push. In transcellular shift states (TPP, refeeding, DKA treatment) use reduced total doses — rebound hyperkalemia is the trap.',
      },
    ],
    references: [
      {
        label: 'Hypokalemia: a clinical update',
        source: 'Kardalas E et al — Endocr Connect 7(4):R135–R146',
        year: '2018',
        url: 'https://doi.org/10.1530/EC-18-0109',
      },
      {
        label: 'Potassium homeostasis and management of dyskalemia in kidney diseases (KDIGO Controversies Conference)',
        source: 'Clase CM et al — Kidney Int 97(1):42–61',
        year: '2020',
        url: 'https://pubmed.ncbi.nlm.nih.gov/31706619/',
      },
      {
        label: 'Potassium disorders: clinical spectrum and emergency management',
        source: 'Alfonzo AVM et al — Resuscitation 70:10–25',
        year: '2006',
        url: 'https://pubmed.ncbi.nlm.nih.gov/16740386/',
      },
    ],
    lastReviewed: '2026-08',
  },

  // ───────────────────────────── PITUITARY ─────────────────────────────
  {
    id: 'pituitary-apoplexy',
    name: 'Pituitary Apoplexy',
    category: 'pituitary',
    summary: 'Acute hemorrhage or infarction of the pituitary, usually into a pre-existing (often unknown) adenoma — a neuro-ophthalmic emergency whose immediate life threat is acute secondary adrenal insufficiency. Give stress-dose steroids before any imaging delay; urgent transsphenoidal decompression (≤7 days) for deteriorating vision or consciousness.',
    firstActions: [
      'HYDROCORTISONE BEFORE ANYTHING ELSE: 100–200 mg IV bolus, then 50–100 mg IM/IV q6h OR a continuous infusion of 2–4 mg/h — empirically for hemodynamic instability, altered consciousness, reduced visual acuity, or severe field defect. Do NOT wait for the cortisol result or the MRI; adrenal crisis is the main early killer.',
      'Draw the pituitary panel BEFORE steroids only if it will not delay them: random cortisol, TSH/FT4, prolactin, IGF-1, LH/FSH + testosterone (men)/estradiol (women), electrolytes, renal/liver function, CBC, coagulation.',
      'Urgent MRI with a dedicated pituitary protocol — the imaging of choice; CT only if MRI is contraindicated or unavailable (noncontrast CT can miss it).',
      'Neurosurgery + ophthalmology consult; document acuity, fields, and ocular motility serially (Pituitary Apoplexy Score, 0–10) and arrange transfer to a neurosurgical center once stabilized.',
      'Levothyroxine ONLY AFTER glucocorticoids are established — starting LT4 first can precipitate or worsen adrenal crisis.',
    ],
    features: [
      'Sudden severe ("thunderclap") retro-orbital or frontal headache — the most common symptom — with nausea and vomiting.',
      'Visual deterioration: reduced acuity and field defects (bitemporal hemianopia from chiasm compression); ophthalmoplegia with diplopia or ptosis (CN III, IV, VI in the cavernous sinus).',
      'Meningismus and photophobia, mimicking subarachnoid hemorrhage or meningitis; decreased consciousness if severe.',
      'Acute hypopituitarism — especially secondary ADRENAL INSUFFICIENCY causing hypotension, hypoglycemia, and hyponatremia; this is the immediate killer.',
      'Precipitants: anticoagulation/antiplatelets, cardiac surgery, hypertension, dynamic pituitary testing, dopamine agonists, pregnancy — but frequently spontaneous.',
    ],
    diagnosis: [
      'Urgent pituitary MRI (the study of choice; CT if MRI contraindicated/unavailable, and to exclude subarachnoid hemorrhage).',
      'Pituitary axes: cortisol (the urgent one — a later 9 AM cortisol <550 nmol/L, ~20 mcg/dL, supports steroid need), free T4 and TSH, prolactin, IGF-1, LH/FSH with testosterone or estradiol — plus electrolytes and glucose.',
      'Watch sodium: secondary adrenal insufficiency and SIADH cause hyponatremia, while concurrent diabetes insipidus causes hypernatremia.',
      'Pituitary Apoplexy Score (0–10: GCS, visual acuity, fields, ocular paresis) tracks severity and is used to follow conservative management.',
    ],
    management: [
      'Stress-dose GLUCOCORTICOIDS immediately: hydrocortisone 100–200 mg IV bolus, then 50–100 mg IM/IV q6h or 2–4 mg/h infusion; taper to oral 20–30 mg/day when stable. Empiric indications: hemodynamic instability, altered consciousness, reduced visual acuity, severe field defect.',
      'Hemodynamic resuscitation with fluids; correct electrolytes (hyponatremia is common — mixed SIADH + adrenal; manage cautiously); analgesia; treat coagulopathy; cardiac monitoring (SAH-like arrhythmias).',
      'Levothyroxine only AFTER glucocorticoid is on board; sex steroids and growth hormone are addressed later.',
      'DECISION — urgent transsphenoidal surgical decompression vs conservative: SURGERY for deteriorating visual acuity, severe or persistent visual field defect, or deteriorating consciousness — preferably WITHIN 7 DAYS of symptom onset (UK guideline). CONSERVATIVE is acceptable when the neuro-ophthalmic exam is intact or mildly impaired and stable/improving — with serial formal visual assessment and a low threshold to convert.',
      '2024 reviews: surgery vs conservative remains an equipoise decision driven by neuro-ophthalmic status, individualized by the MDT (endocrine + neurosurgery + ophthalmology); visual outcomes are similar in carefully selected patients.',
      'Post-acute: full pituitary axis reassessment — ~80% have residual hypopituitarism; long-term imaging surveillance (regrowth risk ~20% at 5 yr).',
    ],
    followUp: [
      'Manage in a NEUROSURGICAL CENTER with HDU capability plus endocrine and ophthalmology input; transfer once stabilized.',
      'Serial neuro-ophthalmic exams (acuity, fields, ocular motility) at least daily during conservative management; daily electrolytes — DI and delayed hyponatremia both occur.',
      'Full pituitary hormone assessment and long-term replacement; serial visual fields and acuity; interval imaging of any residual tumor.',
      'Counsel that apoplexy is often the first presentation of a previously unknown pituitary adenoma.',
    ],
    pearls: [
      'Steroids before thyroid hormone — and before any imaging delay. Hypotension and hyponatremia are the tells of the unrecognized cortisol deficiency.',
      'Thunderclap headache with an ophthalmoplegia or a visual-field cut points to apoplexy; it mimics subarachnoid hemorrhage and bacterial meningitis — request a dedicated pituitary MRI (noncontrast CT can miss it).',
      'Progressive visual loss is the trigger for urgent decompression — do not watch it conservatively; surgery normalizes acuity in ~50% and is time-sensitive (III/IV/VI palsies are often irreversible).',
      'Miss the post-apoplexy/post-op DI and delayed hyponatremia (triphasic pattern) at your peril — daily sodium.',
    ],
    tables: [
      {
        title: 'Pituitary axes in apoplexy — assess all, act on adrenal',
        columns: ['Axis', 'Test', 'Acute action'],
        rows: [
          ['Adrenal (ACTH–cortisol)', 'Random cortisol (9 AM <550 nmol/L supports need)', 'Stress-dose hydrocortisone NOW — do not wait'],
          ['Thyroid', 'Free T4, TSH', 'Replace levothyroxine only AFTER steroids'],
          ['Lactotroph', 'Prolactin', 'Low or high; a high level suggests a prolactinoma'],
          ['Gonadal', 'LH/FSH, testosterone or estradiol', 'Replace later'],
          ['Somatotroph', 'IGF-1', 'Assess later'],
          ['Posterior pituitary', 'Sodium, urine output', 'Watch for SIADH (low Na) or DI (high Na)'],
        ],
        note: 'The adrenal axis is the emergency; every other axis is assessed but managed after the patient is stabilized and glucocorticoid-replaced.',
      },
      {
        title: 'Surgery vs conservative management',
        columns: ['Path', 'Indication', 'Key points'],
        rows: [
          ['Urgent transsphenoidal decompression', 'Deteriorating visual acuity; severe/persistent field defect; deteriorating consciousness', 'Operate preferably ≤7 days from onset (UK 2011); time-sensitive for acuity recovery'],
          ['Conservative', 'Neuro-ophthalmic exam intact or mildly impaired and stable/improving', 'Serial formal visual assessment ≥ daily; low threshold to convert; track with Pituitary Apoplexy Score'],
        ],
        note: 'Equipoise decision driven by neuro-ophthalmic status (2024 reviews) — individualized by endocrine + neurosurgery + ophthalmology MDT; the 2011 UK guideline remains the reference standard.',
      },
    ],
    references: [
      {
        label: 'UK guidelines for the management of pituitary apoplexy',
        source: 'UK Society for Endocrinology / Pituitary Foundation (Rajasekaran S et al) — Clin Endocrinol (Oxf) 74(1):9–20',
        year: '2011',
        url: 'https://doi.org/10.1111/j.1365-2265.2010.03913.x',
      },
      {
        label: 'Pituitary Apoplexy: An Updated Review',
        source: 'Bagetti B, Simó R — J Clin Med 13(9):2508',
        year: '2024',
        url: 'https://doi.org/10.3390/jcm13092508',
      },
      {
        label: 'Diagnosis and Treatment of Pituitary Apoplexy, A True Endocrine Emergency',
        source: 'Maiti T et al — Gac Med Mex 160(3)',
        year: '2024',
        url: 'https://www.sciencedirect.com/science/article/abs/pii/S0188440924000547',
      },
      {
        label: 'Long-term outcomes after haemorrhagic apoplexy in pituitary adenoma managed operatively and non-operatively',
        source: 'Budohoski KP et al — Acta Neurochir 164:1115–1123',
        year: '2022',
        url: 'https://pubmed.ncbi.nlm.nih.gov/35039959/',
      },
    ],
    lastReviewed: '2026-08',
  },
  {
    id: 'central-diabetes-insipidus',
    name: 'Diabetes Insipidus (AVP Deficiency)',
    category: 'pituitary',
    summary: 'Failure of vasopressin secretion (AVP deficiency, formerly central DI) or renal response (AVP resistance, formerly nephrogenic DI) — large volumes of dilute urine with a rising sodium. The classic acute setting is post–pituitary surgery, where the dangers are rapid hypernatremia, omitted DDAVP, and the triphasic swing between DI and SIADH.',
    firstActions: [
      'Hourly urine output + fluid balance and serum Na q6–12h acutely — the trigger: urine >250–300 mL/h × 2 consecutive hours + urine osm <300 mOsm/kg (or SG <1.005) + rising Na = post-op AVP-D.',
      'Match losses with free water (enteral preferred; D5W or 0.45% saline if IV) so the patient does not out-urinate intake; correct established hypernatremia within rate limits (≤10–12 mEq/L per 24 h).',
      'Confirmed AVP-D with symptomatic polyuria/hypernatremia: DDAVP 1–2 mcg IV/SC ON DEMAND (Pituitary Society Delphi consensus) — AVOID the intranasal route after transsphenoidal surgery (unreliable mucosa); oral 0.05–0.1 mg (or 60–120 mcg melt) q8–12h is the alternative.',
      'In ESTABLISHED AVP-D admitted for anything: NEVER omit or delay DDAVP (NHS patient-safety alert — omitted doses in NPO/unconscious patients are a documented cause of inpatient deaths); prescribe it on admission.',
      'Allow a daily DDAVP "escape" (breakthrough polyuria) before the next scheduled dose — fixed scheduled dosing without escape is how hyponatremia happens.',
    ],
    features: [
      'Abrupt polyuria >3 L/24 h (>40–50 mL/kg/24 h) with dilute, near-colorless urine; intense thirst if the patient is awake with water access.',
      'Hypernatremia and hyperosmolality develop fast once intake cannot keep pace — sedated, post-op, unconscious, or ADIPSIC patients are at highest risk because thirst cannot protect them.',
      'Post-neurosurgical triphasic response: (1) early DI days 0–3 (axonal shock) → (2) transient SIADH/antidiuresis ~days 4–7 (release of stored AVP) → (3) possible permanent DI — sodium can swing in either direction.',
      'Nomenclature (2022 working group, reinforced Nat Rev Endocrinol 2024): "central DI" → arginine vasopressin deficiency (AVP-D); "nephrogenic DI" → AVP resistance (AVP-R) — renamed to avoid confusion with diabetes mellitus and dangerous medication errors.',
    ],
    diagnosis: [
      'Virtually diagnostic at the bedside: polyuria with urine osm <300 mOsm/kg PLUS concurrent high-normal/high serum osmolality or Na — NO water deprivation test needed in that setting; exclude osmotic diuresis (glucose, mannitol, urea, recovery phase of AKI) first.',
      'Copeptin-based differentiation is now the gold standard (CARGO, NEJM 2023): hypertonic-saline–STIMULATED copeptin ≤4.9 pmol/L = AVP-D (complete <2.7, partial 2.7–4.9); >4.9 = primary polydipsia — 95.6% accuracy, replacing the water deprivation test.',
      'BASAL (unstimulated) copeptin ≥21.4 pmol/L with Na >147 = AVP-R — a high rule-in value with no stimulation needed.',
      'Arginine-stimulated copeptin (<3.8 pmol/L suggests AVP-D) is only 74.4% accurate — an inferior alternative when hypertonic saline is unsafe.',
      'CARGO hypertonic-saline protocol: 250 mL bolus of 3% NaCl then 0.15 mL/kg/min infusion; stop when Na >149–150 mEq/L and draw copeptin, then an oral water load 30 mL/kg + 500 mL D5W to re-lower Na. Caution/contraindicated in severe baseline hypernatremia and uncontrolled epilepsy.',
      'After confirming AVP-D: pituitary MRI (stalk thickening, absent posterior bright spot), anterior pituitary panel, and etiologic workup (post-op/trauma, infiltrative, autoimmune, germline if young).',
      'Unrecognized cortisol deficiency can MASK DI — replacing glucocorticoid can unmask the polyuria.',
    ],
    management: [
      'Surveillance: hourly urine output + fluid balance; serum Na q6–12h acutely then daily ×7–10 days — to catch both early DI and the later SIADH/triphasic phase (delayed hyponatremia can occur after discharge; advise a Na recheck ~day 7).',
      'DDAVP dosing — parenteral (IV/SC) 1–2 mcg (onset minutes, duration 6–14 h); intranasal 10 mcg (1 spray) q12–24h but AVOID after transsphenoidal surgery; oral 0.05–0.1 mg tablet (or 60–120 mcg lyophilisate/melt) q8–12h.',
      'Post-op strategy: "on demand" dosing for symptomatic polyuria + hypernatremia (Pituitary Society Delphi); let each dose wear off between doses to reveal whether AVP function is returning — over-treatment during the SIADH phase causes dangerous hyponatremia.',
      'Fluid replacement: match urine losses with free water (enteral preferred; D5W/0.45% if IV); correct established hypernatremia at ≤10–12 mEq/L per 24 h.',
      'Chronic AVP-D safety (SfE 2018 / NHS England principles): never omit or delay DDAVP; daily Na, weights, and fluid balance while inpatient; adipsic patients → FIXED daily fluid prescription + daily weights + frequent Na; patient education and an alert bracelet.',
      'AVP-R (nephrogenic): DDAVP is ineffective. Stop the cause (lithium, correct hypercalcemia/hypokalemia); low-solute (low salt/protein) diet; hydrochlorothiazide 25–50 mg/day ± amiloride 5 mg/day (preferred with lithium — blocks ENaC lithium entry); indomethacin in selective cases; genetic testing early in congenital cases (2024 Nat Rev Nephrol consensus).',
    ],
    followUp: [
      'ICU/stepdown for new post-op DI with hypernatremia or adipsia; floor once on stable DDAVP with intact thirst and reliable access to water.',
      'Endocrine consult for all cases; endocrine follow-up for anterior pituitary reassessment and MRI.',
      'Establish permanence and cause, then maintenance DDAVP with an explicit "let it wear off" rule and education on steady dosing, daily breakthrough, and avoiding excess free water.',
      'Screen the anterior pituitary axes — cortisol especially.',
    ],
    pearls: [
      'Dilute urine in the face of a HIGH sodium is the tell — large volumes of pale urine while the sodium climbs is DI until proven otherwise.',
      'Hyponatremia with seizures from DDAVP + uncontrolled water intake is the main chronic toxicity — use the escape method and the lowest effective dose.',
      'Hypernatremic dehydration from omitted or withheld DDAVP in NPO/unconscious AVP-D patients is a documented cause of inpatient deaths — never omit it.',
      'Intranasal DDAVP immediately post-transsphenoidal surgery absorbs poorly or not at all — use parenteral or oral.',
      'Chasing urine output with hourly IV water while on long-acting DDAVP produces wild Na swings; use scheduled dosing plus free water to thirst.',
      'Triphasic trap: a patient stable on DDAVP who becomes hyponatremic mid-week needs DDAVP HELD, not escalated.',
      'Giving DDAVP in AVP-R is ineffective (water overload) — and never diagnose DI without excluding osmotic diuresis.',
    ],
    tables: [
      {
        title: 'Copeptin-based differentiation (CARGO, NEJM 2023)',
        columns: ['Test', 'AVP-D (central)', 'AVP-R (nephrogenic)', 'Primary polydipsia'],
        rows: [
          ['Water deprivation → urine osm', 'Stays <300, then ↑ >50% after DDAVP (complete)', 'Stays low, no/minimal DDAVP response', 'Concentrates >800, no DDAVP effect'],
          ['Basal copeptin (unstimulated)', 'Low–normal overlap', '≥21.4 pmol/L (with Na >147) = rule-in AVP-R', 'Intermediate overlap'],
          ['Hypertonic saline–stimulated copeptin', '≤4.9 pmol/L (complete <2.7; partial 2.7–4.9)', 'High', '>4.9 pmol/L — 95.6% accuracy, gold standard'],
          ['Arginine-stimulated copeptin', '<3.8 pmol/L suggests AVP-D', '—', '>3.8 — only 74.4% accuracy; inferior alternative'],
        ],
        note: 'Stimulated copeptin has replaced the water deprivation test as the diagnostic gold standard for AVP-D; basal copeptin ≥21.4 pmol/L rules in AVP-R without any stimulation test.',
      },
      {
        title: 'DDAVP routes and dosing',
        columns: ['Route', 'Dose', 'Notes'],
        rows: [
          ['IV / SC (parenteral)', '1–2 mcg', 'Onset minutes, duration 6–14 h; preferred post-op'],
          ['Intranasal', '10 mcg (1 spray) q12–24h', 'AVOID after transsphenoidal surgery — unreliable mucosa'],
          ['Oral', '0.05–0.1 mg tablet (or 60–120 mcg melt) q8–12h', 'Outpatient maintenance'],
        ],
        note: 'Post-op: dose on demand and let it wear off between doses (Pituitary Society Delphi); chronic: never omit DDAVP, and allow a daily breakthrough to prevent hyponatremia.',
      },
      {
        title: 'AVP deficiency vs AVP resistance',
        columns: ['Feature', 'AVP-D (central)', 'AVP-R (nephrogenic)'],
        rows: [
          ['Defect', 'Deficient AVP secretion', 'Renal resistance to AVP'],
          ['Response to desmopressin', 'Urine osm rises >50%', 'Little or no rise'],
          ['Copeptin', 'Low (stimulated ≤4.9 pmol/L)', 'High (basal ≥21.4 pmol/L rules in)'],
          ['Common causes', 'Surgery, tumor, trauma, hypophysitis, infiltrative', 'Lithium, hypercalcemia, hypokalemia, hereditary'],
          ['Treatment', 'Desmopressin', 'Stop cause; HCTZ 25–50 mg/d ± amiloride 5 mg/d; low-solute diet'],
        ],
        note: 'A desmopressin trial is the bedside discriminator — AVP-D concentrates the urine; AVP-R does not.',
      },
    ],
    references: [
      {
        label: 'Arginine or Hypertonic Saline–Stimulated Copeptin to Diagnose AVP Deficiency (CARGO trial)',
        source: 'Refardt J et al — N Engl J Med 389:1877–1887',
        year: '2023',
        url: 'https://www.nejm.org/doi/full/10.1056/NEJMoa2306263',
      },
      {
        label: 'Arginine vasopressin deficiency: diagnosis, management and the relevance of oxytocin deficiency',
        source: 'Refardt J, Atila C, Christ-Crain M — Nat Rev Endocrinol 20(8):487–500',
        year: '2024',
        url: 'https://doi.org/10.1038/s41574-024-00985-x',
      },
      {
        label: 'Clinical Guidance: Inpatient management of cranial diabetes insipidus',
        source: 'Society for Endocrinology (Levy M, Prentice M, Wass J) — Endocr Connect 7(7):G8–G11',
        year: '2018',
        url: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6013691/',
      },
      {
        label: 'Delphi survey: endocrine management of patients undergoing transsphenoidal surgery',
        source: 'Pituitary Society (Gadelha M et al) — Pituitary 24:565–576',
        year: '2021',
        url: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8294287/',
      },
      {
        label: 'Diagnosis and management of congenital nephrogenic diabetes insipidus (AVP resistance)',
        source: 'International expert consensus (Bockenhauer D et al) — Nat Rev Nephrol',
        year: '2024',
        url: 'https://www.nature.com/articles/s41581-024-00897-z',
      },
    ],
    lastReviewed: '2026-08',
  },
]
